// Code generated by protoc-gen-go. DO NOT EDIT.
// source: scheduler.proto

package protocol

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ApplicationState int32

const (
	ApplicationState_UNKNOWN  ApplicationState = 0
	ApplicationState_STOPPED  ApplicationState = 1
	ApplicationState_STARTING ApplicationState = 2
	ApplicationState_RUNNING  ApplicationState = 3
)

var ApplicationState_name = map[int32]string{
	0: "UNKNOWN",
	1: "STOPPED",
	2: "STARTING",
	3: "RUNNING",
}

var ApplicationState_value = map[string]int32{
	"UNKNOWN":  0,
	"STOPPED":  1,
	"STARTING": 2,
	"RUNNING":  3,
}

func (x ApplicationState) String() string {
	return proto.EnumName(ApplicationState_name, int32(x))
}

func (ApplicationState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2b3fc28395a6d9c5, []int{0}
}

type GetApplicationLogsResponse_Output int32

const (
	GetApplicationLogsResponse_STDOUT GetApplicationLogsResponse_Output = 0
	GetApplicationLogsResponse_STDERR GetApplicationLogsResponse_Output = 1
)

var GetApplicationLogsResponse_Output_name = map[int32]string{
	0: "STDOUT",
	1: "STDERR",
}

var GetApplicationLogsResponse_Output_value = map[string]int32{
	"STDOUT": 0,
	"STDERR": 1,
}

func (x GetApplicationLogsResponse_Output) String() string {
	return proto.EnumName(GetApplicationLogsResponse_Output_name, int32(x))
}

func (GetApplicationLogsResponse_Output) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2b3fc28395a6d9c5, []int{9, 0}
}

type TestConnectionRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestConnectionRequest) Reset()         { *m = TestConnectionRequest{} }
func (m *TestConnectionRequest) String() string { return proto.CompactTextString(m) }
func (*TestConnectionRequest) ProtoMessage()    {}
func (*TestConnectionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3fc28395a6d9c5, []int{0}
}

func (m *TestConnectionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestConnectionRequest.Unmarshal(m, b)
}
func (m *TestConnectionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestConnectionRequest.Marshal(b, m, deterministic)
}
func (m *TestConnectionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestConnectionRequest.Merge(m, src)
}
func (m *TestConnectionRequest) XXX_Size() int {
	return xxx_messageInfo_TestConnectionRequest.Size(m)
}
func (m *TestConnectionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TestConnectionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TestConnectionRequest proto.InternalMessageInfo

func (m *TestConnectionRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type TestConnectionResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestConnectionResponse) Reset()         { *m = TestConnectionResponse{} }
func (m *TestConnectionResponse) String() string { return proto.CompactTextString(m) }
func (*TestConnectionResponse) ProtoMessage()    {}
func (*TestConnectionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3fc28395a6d9c5, []int{1}
}

func (m *TestConnectionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestConnectionResponse.Unmarshal(m, b)
}
func (m *TestConnectionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestConnectionResponse.Marshal(b, m, deterministic)
}
func (m *TestConnectionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestConnectionResponse.Merge(m, src)
}
func (m *TestConnectionResponse) XXX_Size() int {
	return xxx_messageInfo_TestConnectionResponse.Size(m)
}
func (m *TestConnectionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TestConnectionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TestConnectionResponse proto.InternalMessageInfo

func (m *TestConnectionResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type Application struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Image                string            `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Replicas             uint32            `protobuf:"varint,4,opt,name=replicas,proto3" json:"replicas,omitempty"`
	Environment          map[string]string `protobuf:"bytes,5,rep,name=environment,proto3" json:"environment,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Application) Reset()         { *m = Application{} }
func (m *Application) String() string { return proto.CompactTextString(m) }
func (*Application) ProtoMessage()    {}
func (*Application) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3fc28395a6d9c5, []int{2}
}

func (m *Application) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Application.Unmarshal(m, b)
}
func (m *Application) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Application.Marshal(b, m, deterministic)
}
func (m *Application) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Application.Merge(m, src)
}
func (m *Application) XXX_Size() int {
	return xxx_messageInfo_Application.Size(m)
}
func (m *Application) XXX_DiscardUnknown() {
	xxx_messageInfo_Application.DiscardUnknown(m)
}

var xxx_messageInfo_Application proto.InternalMessageInfo

func (m *Application) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Application) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Application) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *Application) GetReplicas() uint32 {
	if m != nil {
		return m.Replicas
	}
	return 0
}

func (m *Application) GetEnvironment() map[string]string {
	if m != nil {
		return m.Environment
	}
	return nil
}

type DeployApplicationRequest struct {
	Application          *Application `protobuf:"bytes,1,opt,name=application,proto3" json:"application,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *DeployApplicationRequest) Reset()         { *m = DeployApplicationRequest{} }
func (m *DeployApplicationRequest) String() string { return proto.CompactTextString(m) }
func (*DeployApplicationRequest) ProtoMessage()    {}
func (*DeployApplicationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3fc28395a6d9c5, []int{3}
}

func (m *DeployApplicationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeployApplicationRequest.Unmarshal(m, b)
}
func (m *DeployApplicationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeployApplicationRequest.Marshal(b, m, deterministic)
}
func (m *DeployApplicationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeployApplicationRequest.Merge(m, src)
}
func (m *DeployApplicationRequest) XXX_Size() int {
	return xxx_messageInfo_DeployApplicationRequest.Size(m)
}
func (m *DeployApplicationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeployApplicationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeployApplicationRequest proto.InternalMessageInfo

func (m *DeployApplicationRequest) GetApplication() *Application {
	if m != nil {
		return m.Application
	}
	return nil
}

type DeployApplicationResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeployApplicationResponse) Reset()         { *m = DeployApplicationResponse{} }
func (m *DeployApplicationResponse) String() string { return proto.CompactTextString(m) }
func (*DeployApplicationResponse) ProtoMessage()    {}
func (*DeployApplicationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3fc28395a6d9c5, []int{4}
}

func (m *DeployApplicationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeployApplicationResponse.Unmarshal(m, b)
}
func (m *DeployApplicationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeployApplicationResponse.Marshal(b, m, deterministic)
}
func (m *DeployApplicationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeployApplicationResponse.Merge(m, src)
}
func (m *DeployApplicationResponse) XXX_Size() int {
	return xxx_messageInfo_DeployApplicationResponse.Size(m)
}
func (m *DeployApplicationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeployApplicationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeployApplicationResponse proto.InternalMessageInfo

type DeleteApplicationRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteApplicationRequest) Reset()         { *m = DeleteApplicationRequest{} }
func (m *DeleteApplicationRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteApplicationRequest) ProtoMessage()    {}
func (*DeleteApplicationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3fc28395a6d9c5, []int{5}
}

func (m *DeleteApplicationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteApplicationRequest.Unmarshal(m, b)
}
func (m *DeleteApplicationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteApplicationRequest.Marshal(b, m, deterministic)
}
func (m *DeleteApplicationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteApplicationRequest.Merge(m, src)
}
func (m *DeleteApplicationRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteApplicationRequest.Size(m)
}
func (m *DeleteApplicationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteApplicationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteApplicationRequest proto.InternalMessageInfo

func (m *DeleteApplicationRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteApplicationResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteApplicationResponse) Reset()         { *m = DeleteApplicationResponse{} }
func (m *DeleteApplicationResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteApplicationResponse) ProtoMessage()    {}
func (*DeleteApplicationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3fc28395a6d9c5, []int{6}
}

func (m *DeleteApplicationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteApplicationResponse.Unmarshal(m, b)
}
func (m *DeleteApplicationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteApplicationResponse.Marshal(b, m, deterministic)
}
func (m *DeleteApplicationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteApplicationResponse.Merge(m, src)
}
func (m *DeleteApplicationResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteApplicationResponse.Size(m)
}
func (m *DeleteApplicationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteApplicationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteApplicationResponse proto.InternalMessageInfo

type GetApplicationLogsRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetApplicationLogsRequest) Reset()         { *m = GetApplicationLogsRequest{} }
func (m *GetApplicationLogsRequest) String() string { return proto.CompactTextString(m) }
func (*GetApplicationLogsRequest) ProtoMessage()    {}
func (*GetApplicationLogsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3fc28395a6d9c5, []int{7}
}

func (m *GetApplicationLogsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetApplicationLogsRequest.Unmarshal(m, b)
}
func (m *GetApplicationLogsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetApplicationLogsRequest.Marshal(b, m, deterministic)
}
func (m *GetApplicationLogsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetApplicationLogsRequest.Merge(m, src)
}
func (m *GetApplicationLogsRequest) XXX_Size() int {
	return xxx_messageInfo_GetApplicationLogsRequest.Size(m)
}
func (m *GetApplicationLogsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetApplicationLogsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetApplicationLogsRequest proto.InternalMessageInfo

func (m *GetApplicationLogsRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Timestamp struct {
	Second               int64    `protobuf:"varint,1,opt,name=second,proto3" json:"second,omitempty"`
	NanoSecond           int64    `protobuf:"varint,2,opt,name=nanoSecond,proto3" json:"nanoSecond,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Timestamp) Reset()         { *m = Timestamp{} }
func (m *Timestamp) String() string { return proto.CompactTextString(m) }
func (*Timestamp) ProtoMessage()    {}
func (*Timestamp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3fc28395a6d9c5, []int{8}
}

func (m *Timestamp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Timestamp.Unmarshal(m, b)
}
func (m *Timestamp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Timestamp.Marshal(b, m, deterministic)
}
func (m *Timestamp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Timestamp.Merge(m, src)
}
func (m *Timestamp) XXX_Size() int {
	return xxx_messageInfo_Timestamp.Size(m)
}
func (m *Timestamp) XXX_DiscardUnknown() {
	xxx_messageInfo_Timestamp.DiscardUnknown(m)
}

var xxx_messageInfo_Timestamp proto.InternalMessageInfo

func (m *Timestamp) GetSecond() int64 {
	if m != nil {
		return m.Second
	}
	return 0
}

func (m *Timestamp) GetNanoSecond() int64 {
	if m != nil {
		return m.NanoSecond
	}
	return 0
}

type GetApplicationLogsResponse struct {
	Output               GetApplicationLogsResponse_Output `protobuf:"varint,1,opt,name=output,proto3,enum=protocol.GetApplicationLogsResponse_Output" json:"output,omitempty"`
	Time                 *Timestamp                        `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	TaskId               string                            `protobuf:"bytes,3,opt,name=taskId,proto3" json:"taskId,omitempty"`
	Message              string                            `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *GetApplicationLogsResponse) Reset()         { *m = GetApplicationLogsResponse{} }
func (m *GetApplicationLogsResponse) String() string { return proto.CompactTextString(m) }
func (*GetApplicationLogsResponse) ProtoMessage()    {}
func (*GetApplicationLogsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3fc28395a6d9c5, []int{9}
}

func (m *GetApplicationLogsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetApplicationLogsResponse.Unmarshal(m, b)
}
func (m *GetApplicationLogsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetApplicationLogsResponse.Marshal(b, m, deterministic)
}
func (m *GetApplicationLogsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetApplicationLogsResponse.Merge(m, src)
}
func (m *GetApplicationLogsResponse) XXX_Size() int {
	return xxx_messageInfo_GetApplicationLogsResponse.Size(m)
}
func (m *GetApplicationLogsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetApplicationLogsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetApplicationLogsResponse proto.InternalMessageInfo

func (m *GetApplicationLogsResponse) GetOutput() GetApplicationLogsResponse_Output {
	if m != nil {
		return m.Output
	}
	return GetApplicationLogsResponse_STDOUT
}

func (m *GetApplicationLogsResponse) GetTime() *Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *GetApplicationLogsResponse) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func (m *GetApplicationLogsResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterEnum("protocol.ApplicationState", ApplicationState_name, ApplicationState_value)
	proto.RegisterEnum("protocol.GetApplicationLogsResponse_Output", GetApplicationLogsResponse_Output_name, GetApplicationLogsResponse_Output_value)
	proto.RegisterType((*TestConnectionRequest)(nil), "protocol.TestConnectionRequest")
	proto.RegisterType((*TestConnectionResponse)(nil), "protocol.TestConnectionResponse")
	proto.RegisterType((*Application)(nil), "protocol.Application")
	proto.RegisterMapType((map[string]string)(nil), "protocol.Application.EnvironmentEntry")
	proto.RegisterType((*DeployApplicationRequest)(nil), "protocol.DeployApplicationRequest")
	proto.RegisterType((*DeployApplicationResponse)(nil), "protocol.DeployApplicationResponse")
	proto.RegisterType((*DeleteApplicationRequest)(nil), "protocol.DeleteApplicationRequest")
	proto.RegisterType((*DeleteApplicationResponse)(nil), "protocol.DeleteApplicationResponse")
	proto.RegisterType((*GetApplicationLogsRequest)(nil), "protocol.GetApplicationLogsRequest")
	proto.RegisterType((*Timestamp)(nil), "protocol.Timestamp")
	proto.RegisterType((*GetApplicationLogsResponse)(nil), "protocol.GetApplicationLogsResponse")
}

func init() { proto.RegisterFile("scheduler.proto", fileDescriptor_2b3fc28395a6d9c5) }

var fileDescriptor_2b3fc28395a6d9c5 = []byte{
	// 577 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0xd1, 0x6e, 0xd3, 0x30,
	0x14, 0x6d, 0x92, 0xae, 0xeb, 0x6e, 0x60, 0x04, 0xc3, 0xa6, 0xac, 0x48, 0x50, 0x65, 0x08, 0xaa,
	0x4d, 0x54, 0xa8, 0x3c, 0x80, 0x78, 0x40, 0x9a, 0xd6, 0xaa, 0x4c, 0xa0, 0x74, 0x72, 0x52, 0xf1,
	0x86, 0x14, 0xd2, 0xab, 0x11, 0x35, 0xb1, 0x43, 0xed, 0x4e, 0xea, 0x17, 0xf0, 0x97, 0xfc, 0x01,
	0xff, 0x80, 0xe2, 0xa4, 0x6b, 0xda, 0xa6, 0x13, 0x4f, 0xf1, 0xf1, 0x3d, 0xf7, 0x9c, 0x6b, 0xe7,
	0x18, 0x1e, 0x89, 0xf0, 0x27, 0x4e, 0xe6, 0x31, 0xce, 0xba, 0xe9, 0x8c, 0x4b, 0x4e, 0x9a, 0xea,
	0x13, 0xf2, 0xd8, 0x79, 0x03, 0x47, 0x3e, 0x0a, 0x79, 0xc9, 0x19, 0xc3, 0x50, 0x46, 0x9c, 0x51,
	0xfc, 0x35, 0x47, 0x21, 0xc9, 0x53, 0xd8, 0x93, 0x7c, 0x8a, 0xcc, 0xd6, 0xda, 0x5a, 0xe7, 0x80,
	0xe6, 0xc0, 0xe9, 0xc0, 0xf1, 0x26, 0x5d, 0xa4, 0x9c, 0x09, 0x24, 0x87, 0xa0, 0xf3, 0xa9, 0x22,
	0x37, 0xa9, 0xce, 0xa7, 0xce, 0x5f, 0x0d, 0xcc, 0x8b, 0x34, 0x8d, 0xa3, 0x30, 0xc8, 0x78, 0x59,
	0x3d, 0x9a, 0x14, 0x62, 0x7a, 0x34, 0x21, 0x04, 0xea, 0x2c, 0x48, 0xd0, 0xd6, 0xd5, 0x8e, 0x5a,
	0x67, 0x9e, 0x51, 0x12, 0xdc, 0xa0, 0x6d, 0xe4, 0x9e, 0x0a, 0x90, 0x16, 0x34, 0x67, 0xa8, 0x84,
	0x84, 0x5d, 0x6f, 0x6b, 0x9d, 0x87, 0xf4, 0x0e, 0x93, 0xcf, 0x60, 0x22, 0xbb, 0x8d, 0x66, 0x9c,
	0x25, 0xc8, 0xa4, 0xbd, 0xd7, 0x36, 0x3a, 0x66, 0xef, 0x55, 0x77, 0x79, 0xbc, 0x6e, 0x69, 0x82,
	0xee, 0x60, 0x45, 0x1c, 0x30, 0x39, 0x5b, 0xd0, 0x72, 0x6b, 0xeb, 0x13, 0x58, 0x9b, 0x04, 0x62,
	0x81, 0x31, 0xc5, 0x45, 0x31, 0x74, 0xb6, 0xcc, 0x26, 0xbc, 0x0d, 0xe2, 0xf9, 0x72, 0xec, 0x1c,
	0x7c, 0xd4, 0x3f, 0x68, 0x8e, 0x07, 0x76, 0x1f, 0xd3, 0x98, 0x2f, 0x4a, 0x96, 0xcb, 0xbb, 0x7c,
	0x0f, 0x66, 0xb0, 0xda, 0x55, 0x7a, 0x66, 0xef, 0xa8, 0x72, 0x4a, 0x5a, 0x66, 0x3a, 0xcf, 0xe0,
	0xa4, 0x42, 0x34, 0xbf, 0x71, 0xe7, 0x2c, 0x73, 0x8c, 0x51, 0x62, 0x85, 0xe3, 0xc6, 0x6d, 0xe7,
	0x42, 0x5b, 0xdc, 0x42, 0xe8, 0x1c, 0x4e, 0x86, 0x28, 0x4b, 0x95, 0xaf, 0xfc, 0x46, 0xec, 0x52,
	0xba, 0x84, 0x03, 0x3f, 0x4a, 0x50, 0xc8, 0x20, 0x49, 0xc9, 0x31, 0x34, 0x04, 0x86, 0x9c, 0xe5,
	0x04, 0x83, 0x16, 0x88, 0x3c, 0x07, 0x60, 0x01, 0xe3, 0x5e, 0x5e, 0xd3, 0x55, 0xad, 0xb4, 0xe3,
	0xfc, 0xd1, 0xa0, 0x55, 0x65, 0x59, 0x64, 0xe9, 0x12, 0x1a, 0x7c, 0x2e, 0xd3, 0xb9, 0x54, 0xb2,
	0x87, 0xbd, 0xf3, 0xd5, 0x55, 0xed, 0xee, 0xea, 0x8e, 0x54, 0x0b, 0x2d, 0x5a, 0xc9, 0x6b, 0xa8,
	0xcb, 0xa8, 0x08, 0x98, 0xd9, 0x7b, 0xb2, 0x92, 0xb8, 0x1b, 0x9f, 0x2a, 0x42, 0x76, 0x08, 0x19,
	0x88, 0xe9, 0xd5, 0xa4, 0x88, 0x5d, 0x81, 0x88, 0x0d, 0xfb, 0x09, 0x0a, 0x91, 0xe5, 0xb1, 0xae,
	0x0a, 0x4b, 0xe8, 0xb4, 0xa1, 0x91, 0x9b, 0x11, 0x80, 0x86, 0xe7, 0xf7, 0x47, 0x63, 0xdf, 0xaa,
	0x15, 0xeb, 0x01, 0xa5, 0x96, 0x76, 0x36, 0x04, 0xab, 0x34, 0xa6, 0x27, 0x03, 0x89, 0xc4, 0x84,
	0xfd, 0xb1, 0xfb, 0xc5, 0x1d, 0x7d, 0x73, 0xad, 0x5a, 0x06, 0x3c, 0x7f, 0x74, 0x7d, 0x3d, 0xe8,
	0x5b, 0x1a, 0x79, 0x00, 0x4d, 0xcf, 0xbf, 0xa0, 0xfe, 0x95, 0x3b, 0xb4, 0xf4, 0xac, 0x44, 0xc7,
	0xae, 0x9b, 0x01, 0xa3, 0xf7, 0xdb, 0x80, 0x03, 0x6f, 0xf9, 0x7a, 0xc9, 0x18, 0x0e, 0xd7, 0x9f,
	0x1f, 0x79, 0x51, 0x3a, 0x57, 0xd5, 0x3b, 0x6e, 0xb5, 0x77, 0x13, 0x8a, 0xdf, 0x5f, 0x23, 0xdf,
	0xe1, 0xf1, 0x56, 0xcc, 0x88, 0xb3, 0x6a, 0xdc, 0x15, 0xec, 0xd6, 0xe9, 0xbd, 0x9c, 0x75, 0xfd,
	0x8d, 0xf4, 0xad, 0xeb, 0x57, 0xc7, 0x78, 0x5d, 0x7f, 0x57, 0x7c, 0x6b, 0x24, 0x04, 0xb2, 0x9d,
	0x0b, 0x72, 0x7a, 0x7f, 0x6a, 0x72, 0x87, 0x97, 0xff, 0x13, 0x2d, 0xa7, 0xf6, 0x56, 0xfb, 0xd1,
	0x50, 0xc4, 0x77, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x3b, 0x51, 0x55, 0x60, 0x4d, 0x05, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SchedulerClient is the client API for Scheduler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SchedulerClient interface {
	TestConnection(ctx context.Context, in *TestConnectionRequest, opts ...grpc.CallOption) (*TestConnectionResponse, error)
	DeployApplication(ctx context.Context, in *DeployApplicationRequest, opts ...grpc.CallOption) (*DeployApplicationResponse, error)
	DeleteApplication(ctx context.Context, in *DeleteApplicationRequest, opts ...grpc.CallOption) (*DeleteApplicationResponse, error)
	GetApplicationLogs(ctx context.Context, in *GetApplicationLogsRequest, opts ...grpc.CallOption) (Scheduler_GetApplicationLogsClient, error)
}

type schedulerClient struct {
	cc *grpc.ClientConn
}

func NewSchedulerClient(cc *grpc.ClientConn) SchedulerClient {
	return &schedulerClient{cc}
}

func (c *schedulerClient) TestConnection(ctx context.Context, in *TestConnectionRequest, opts ...grpc.CallOption) (*TestConnectionResponse, error) {
	out := new(TestConnectionResponse)
	err := c.cc.Invoke(ctx, "/protocol.Scheduler/TestConnection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerClient) DeployApplication(ctx context.Context, in *DeployApplicationRequest, opts ...grpc.CallOption) (*DeployApplicationResponse, error) {
	out := new(DeployApplicationResponse)
	err := c.cc.Invoke(ctx, "/protocol.Scheduler/DeployApplication", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerClient) DeleteApplication(ctx context.Context, in *DeleteApplicationRequest, opts ...grpc.CallOption) (*DeleteApplicationResponse, error) {
	out := new(DeleteApplicationResponse)
	err := c.cc.Invoke(ctx, "/protocol.Scheduler/DeleteApplication", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerClient) GetApplicationLogs(ctx context.Context, in *GetApplicationLogsRequest, opts ...grpc.CallOption) (Scheduler_GetApplicationLogsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Scheduler_serviceDesc.Streams[0], "/protocol.Scheduler/GetApplicationLogs", opts...)
	if err != nil {
		return nil, err
	}
	x := &schedulerGetApplicationLogsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Scheduler_GetApplicationLogsClient interface {
	Recv() (*GetApplicationLogsResponse, error)
	grpc.ClientStream
}

type schedulerGetApplicationLogsClient struct {
	grpc.ClientStream
}

func (x *schedulerGetApplicationLogsClient) Recv() (*GetApplicationLogsResponse, error) {
	m := new(GetApplicationLogsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SchedulerServer is the server API for Scheduler service.
type SchedulerServer interface {
	TestConnection(context.Context, *TestConnectionRequest) (*TestConnectionResponse, error)
	DeployApplication(context.Context, *DeployApplicationRequest) (*DeployApplicationResponse, error)
	DeleteApplication(context.Context, *DeleteApplicationRequest) (*DeleteApplicationResponse, error)
	GetApplicationLogs(*GetApplicationLogsRequest, Scheduler_GetApplicationLogsServer) error
}

// UnimplementedSchedulerServer can be embedded to have forward compatible implementations.
type UnimplementedSchedulerServer struct {
}

func (*UnimplementedSchedulerServer) TestConnection(ctx context.Context, req *TestConnectionRequest) (*TestConnectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestConnection not implemented")
}
func (*UnimplementedSchedulerServer) DeployApplication(ctx context.Context, req *DeployApplicationRequest) (*DeployApplicationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeployApplication not implemented")
}
func (*UnimplementedSchedulerServer) DeleteApplication(ctx context.Context, req *DeleteApplicationRequest) (*DeleteApplicationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteApplication not implemented")
}
func (*UnimplementedSchedulerServer) GetApplicationLogs(req *GetApplicationLogsRequest, srv Scheduler_GetApplicationLogsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetApplicationLogs not implemented")
}

func RegisterSchedulerServer(s *grpc.Server, srv SchedulerServer) {
	s.RegisterService(&_Scheduler_serviceDesc, srv)
}

func _Scheduler_TestConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).TestConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.Scheduler/TestConnection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).TestConnection(ctx, req.(*TestConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scheduler_DeployApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeployApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).DeployApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.Scheduler/DeployApplication",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).DeployApplication(ctx, req.(*DeployApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scheduler_DeleteApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).DeleteApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.Scheduler/DeleteApplication",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).DeleteApplication(ctx, req.(*DeleteApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scheduler_GetApplicationLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetApplicationLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SchedulerServer).GetApplicationLogs(m, &schedulerGetApplicationLogsServer{stream})
}

type Scheduler_GetApplicationLogsServer interface {
	Send(*GetApplicationLogsResponse) error
	grpc.ServerStream
}

type schedulerGetApplicationLogsServer struct {
	grpc.ServerStream
}

func (x *schedulerGetApplicationLogsServer) Send(m *GetApplicationLogsResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _Scheduler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protocol.Scheduler",
	HandlerType: (*SchedulerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TestConnection",
			Handler:    _Scheduler_TestConnection_Handler,
		},
		{
			MethodName: "DeployApplication",
			Handler:    _Scheduler_DeployApplication_Handler,
		},
		{
			MethodName: "DeleteApplication",
			Handler:    _Scheduler_DeleteApplication_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetApplicationLogs",
			Handler:       _Scheduler_GetApplicationLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "scheduler.proto",
}
