export const INSTAGRAM_FETCH_POSTS_PENDING = 'INSTAGRAM_FETCH_POSTS_PENDING'
export const INSTAGRAM_FETCH_POSTS_SUCCESS = 'INSTAGRAM_FETCH_POSTS_SUCCESS'
export const INSTAGRAM_FETCH_POSTS_ERROR = 'INSTAGRAM_FETCH_POSTS_ERROR'
