export const INSTAGRAM_FETCH_POST_PENDING = 'INSTAGRAM_FETCH_POST_PENDING'
export const INSTAGRAM_FETCH_POST_SUCCESS = 'INSTAGRAM_FETCH_POST_SUCCESS'
export const INSTAGRAM_FETCH_POST_ERROR = 'INSTAGRAM_FETCH_POST_ERROR'
