export const FETCH_RUNNERS_PENDING = 'FETCH_RUNNERS_PENDING';
export const FETCH_RUNNERS_SUCCESS = 'FETCH_RUNNERS_SUCCESS';
export const FETCH_RUNNERS_ERROR = 'FETCH_RUNNERS_ERROR';

export const ADD_RUNNER = 'ADD_RUNNER';
export const UPDATE_RUNNER = 'UPDATE_RUNNER';
export const DELETE_RUNNER = 'DELETE_RUNNER';

export const CREATE_RUNNER_PENDING = 'CREATE_RUNNER_PENDING';
