// Code generated by protoc-gen-go. DO NOT EDIT.
// source: app.proto

package protocol

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DeploymentEventRequestType int32

const (
	DeploymentEventRequestType_DEPLOY_APP DeploymentEventRequestType = 0
)

var DeploymentEventRequestType_name = map[int32]string{
	0: "DEPLOY_APP",
}

var DeploymentEventRequestType_value = map[string]int32{
	"DEPLOY_APP": 0,
}

func (x DeploymentEventRequestType) String() string {
	return proto.EnumName(DeploymentEventRequestType_name, int32(x))
}

func (DeploymentEventRequestType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{0}
}

type DeploymentEventResponseType int32

const (
	DeploymentEventResponseType_OK    DeploymentEventResponseType = 0
	DeploymentEventResponseType_ERROR DeploymentEventResponseType = 1
)

var DeploymentEventResponseType_name = map[int32]string{
	0: "OK",
	1: "ERROR",
}

var DeploymentEventResponseType_value = map[string]int32{
	"OK":    0,
	"ERROR": 1,
}

func (x DeploymentEventResponseType) String() string {
	return proto.EnumName(DeploymentEventResponseType_name, int32(x))
}

func (DeploymentEventResponseType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{1}
}

type GetTokenRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTokenRequest) Reset()         { *m = GetTokenRequest{} }
func (m *GetTokenRequest) String() string { return proto.CompactTextString(m) }
func (*GetTokenRequest) ProtoMessage()    {}
func (*GetTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{0}
}

func (m *GetTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTokenRequest.Unmarshal(m, b)
}
func (m *GetTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTokenRequest.Marshal(b, m, deterministic)
}
func (m *GetTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTokenRequest.Merge(m, src)
}
func (m *GetTokenRequest) XXX_Size() int {
	return xxx_messageInfo_GetTokenRequest.Size(m)
}
func (m *GetTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTokenRequest proto.InternalMessageInfo

type GetTokenResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTokenResponse) Reset()         { *m = GetTokenResponse{} }
func (m *GetTokenResponse) String() string { return proto.CompactTextString(m) }
func (*GetTokenResponse) ProtoMessage()    {}
func (*GetTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{1}
}

func (m *GetTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTokenResponse.Unmarshal(m, b)
}
func (m *GetTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTokenResponse.Marshal(b, m, deterministic)
}
func (m *GetTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTokenResponse.Merge(m, src)
}
func (m *GetTokenResponse) XXX_Size() int {
	return xxx_messageInfo_GetTokenResponse.Size(m)
}
func (m *GetTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTokenResponse proto.InternalMessageInfo

func (m *GetTokenResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type DeploymentEventRequest struct {
	Type DeploymentEventRequestType `protobuf:"varint,1,opt,name=type,proto3,enum=protocol.DeploymentEventRequestType" json:"type,omitempty"`
	// Types that are valid to be assigned to RequestOneof:
	//	*DeploymentEventRequest_AppDeploymentRequest
	RequestOneof         isDeploymentEventRequest_RequestOneof `protobuf_oneof:"request_oneof"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *DeploymentEventRequest) Reset()         { *m = DeploymentEventRequest{} }
func (m *DeploymentEventRequest) String() string { return proto.CompactTextString(m) }
func (*DeploymentEventRequest) ProtoMessage()    {}
func (*DeploymentEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{2}
}

func (m *DeploymentEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeploymentEventRequest.Unmarshal(m, b)
}
func (m *DeploymentEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeploymentEventRequest.Marshal(b, m, deterministic)
}
func (m *DeploymentEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeploymentEventRequest.Merge(m, src)
}
func (m *DeploymentEventRequest) XXX_Size() int {
	return xxx_messageInfo_DeploymentEventRequest.Size(m)
}
func (m *DeploymentEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeploymentEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeploymentEventRequest proto.InternalMessageInfo

func (m *DeploymentEventRequest) GetType() DeploymentEventRequestType {
	if m != nil {
		return m.Type
	}
	return DeploymentEventRequestType_DEPLOY_APP
}

type isDeploymentEventRequest_RequestOneof interface {
	isDeploymentEventRequest_RequestOneof()
}

type DeploymentEventRequest_AppDeploymentRequest struct {
	AppDeploymentRequest *AppDeploymentRequest `protobuf:"bytes,2,opt,name=appDeploymentRequest,proto3,oneof"`
}

func (*DeploymentEventRequest_AppDeploymentRequest) isDeploymentEventRequest_RequestOneof() {}

func (m *DeploymentEventRequest) GetRequestOneof() isDeploymentEventRequest_RequestOneof {
	if m != nil {
		return m.RequestOneof
	}
	return nil
}

func (m *DeploymentEventRequest) GetAppDeploymentRequest() *AppDeploymentRequest {
	if x, ok := m.GetRequestOneof().(*DeploymentEventRequest_AppDeploymentRequest); ok {
		return x.AppDeploymentRequest
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*DeploymentEventRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*DeploymentEventRequest_AppDeploymentRequest)(nil),
	}
}

type AppDeploymentRequest struct {
	AppName              string   `protobuf:"bytes,1,opt,name=appName,proto3" json:"appName,omitempty"`
	Repository           string   `protobuf:"bytes,2,opt,name=repository,proto3" json:"repository,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppDeploymentRequest) Reset()         { *m = AppDeploymentRequest{} }
func (m *AppDeploymentRequest) String() string { return proto.CompactTextString(m) }
func (*AppDeploymentRequest) ProtoMessage()    {}
func (*AppDeploymentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{3}
}

func (m *AppDeploymentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppDeploymentRequest.Unmarshal(m, b)
}
func (m *AppDeploymentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppDeploymentRequest.Marshal(b, m, deterministic)
}
func (m *AppDeploymentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppDeploymentRequest.Merge(m, src)
}
func (m *AppDeploymentRequest) XXX_Size() int {
	return xxx_messageInfo_AppDeploymentRequest.Size(m)
}
func (m *AppDeploymentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AppDeploymentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AppDeploymentRequest proto.InternalMessageInfo

func (m *AppDeploymentRequest) GetAppName() string {
	if m != nil {
		return m.AppName
	}
	return ""
}

func (m *AppDeploymentRequest) GetRepository() string {
	if m != nil {
		return m.Repository
	}
	return ""
}

type DeploymentEventResponse struct {
	Type                 DeploymentEventResponseType `protobuf:"varint,1,opt,name=type,proto3,enum=protocol.DeploymentEventResponseType" json:"type,omitempty"`
	Message              string                      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *DeploymentEventResponse) Reset()         { *m = DeploymentEventResponse{} }
func (m *DeploymentEventResponse) String() string { return proto.CompactTextString(m) }
func (*DeploymentEventResponse) ProtoMessage()    {}
func (*DeploymentEventResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{4}
}

func (m *DeploymentEventResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeploymentEventResponse.Unmarshal(m, b)
}
func (m *DeploymentEventResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeploymentEventResponse.Marshal(b, m, deterministic)
}
func (m *DeploymentEventResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeploymentEventResponse.Merge(m, src)
}
func (m *DeploymentEventResponse) XXX_Size() int {
	return xxx_messageInfo_DeploymentEventResponse.Size(m)
}
func (m *DeploymentEventResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeploymentEventResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeploymentEventResponse proto.InternalMessageInfo

func (m *DeploymentEventResponse) GetType() DeploymentEventResponseType {
	if m != nil {
		return m.Type
	}
	return DeploymentEventResponseType_OK
}

func (m *DeploymentEventResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterEnum("protocol.DeploymentEventRequestType", DeploymentEventRequestType_name, DeploymentEventRequestType_value)
	proto.RegisterEnum("protocol.DeploymentEventResponseType", DeploymentEventResponseType_name, DeploymentEventResponseType_value)
	proto.RegisterType((*GetTokenRequest)(nil), "protocol.GetTokenRequest")
	proto.RegisterType((*GetTokenResponse)(nil), "protocol.GetTokenResponse")
	proto.RegisterType((*DeploymentEventRequest)(nil), "protocol.DeploymentEventRequest")
	proto.RegisterType((*AppDeploymentRequest)(nil), "protocol.AppDeploymentRequest")
	proto.RegisterType((*DeploymentEventResponse)(nil), "protocol.DeploymentEventResponse")
}

func init() { proto.RegisterFile("app.proto", fileDescriptor_e0f9056a14b86d47) }

var fileDescriptor_e0f9056a14b86d47 = []byte{
	// 354 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x4d, 0x4b, 0xf3, 0x40,
	0x10, 0xc7, 0xb3, 0xe5, 0xe9, 0x4b, 0xe6, 0xc1, 0x36, 0x2e, 0x45, 0x63, 0x84, 0x52, 0x83, 0x42,
	0x28, 0x52, 0x4a, 0xbd, 0xe8, 0xb1, 0xda, 0xa2, 0xa0, 0xd8, 0xb0, 0xf6, 0xe2, 0x41, 0x4a, 0xac,
	0xe3, 0x0b, 0xb6, 0xd9, 0x35, 0xbb, 0x15, 0xf2, 0xa9, 0x3c, 0xfb, 0xed, 0xc4, 0xbc, 0x90, 0x5a,
	0x63, 0x7b, 0x4a, 0x66, 0xf6, 0x3f, 0xf3, 0x9f, 0xf9, 0x31, 0xa0, 0x7b, 0x42, 0xb4, 0x45, 0xc0,
	0x15, 0xa7, 0x95, 0xe8, 0x33, 0xe1, 0x53, 0x7b, 0x13, 0x6a, 0xe7, 0xa8, 0x46, 0xfc, 0x15, 0x7d,
	0x86, 0x6f, 0x73, 0x94, 0xca, 0x76, 0xc0, 0xc8, 0x52, 0x52, 0x70, 0x5f, 0x22, 0xad, 0x43, 0x51,
	0x7d, 0x27, 0x4c, 0xd2, 0x24, 0x8e, 0xce, 0xe2, 0xc0, 0xfe, 0x24, 0xb0, 0xd5, 0x47, 0x31, 0xe5,
	0xe1, 0x0c, 0x7d, 0x35, 0x78, 0x47, 0x5f, 0x25, 0x4d, 0xe8, 0x31, 0xfc, 0x53, 0xa1, 0xc0, 0x48,
	0x5f, 0xed, 0xee, 0xb7, 0x53, 0xc3, 0x76, 0xbe, 0x7e, 0x14, 0x0a, 0x64, 0x51, 0x05, 0x1d, 0x41,
	0xdd, 0x13, 0x22, 0x93, 0x25, 0x0a, 0xb3, 0xd0, 0x24, 0xce, 0xff, 0x6e, 0x23, 0xeb, 0xd4, 0xcb,
	0x51, 0x5d, 0x68, 0x2c, 0xb7, 0xfa, 0xb4, 0x06, 0x1b, 0x41, 0xfc, 0x3b, 0xe6, 0x3e, 0xf2, 0x47,
	0xdb, 0x85, 0x7a, 0x5e, 0x03, 0x6a, 0x42, 0xd9, 0x13, 0xe2, 0xda, 0x9b, 0x61, 0xb2, 0x6b, 0x1a,
	0xd2, 0x06, 0x40, 0x80, 0x82, 0xcb, 0x17, 0xc5, 0x83, 0x30, 0x1a, 0x47, 0x67, 0x0b, 0x19, 0xdb,
	0x87, 0xed, 0x5f, 0xcb, 0x25, 0xf8, 0x4e, 0x7e, 0xd0, 0x38, 0x58, 0x41, 0x23, 0x2e, 0x58, 0xc0,
	0x61, 0x42, 0x79, 0x86, 0x52, 0x7a, 0x4f, 0x98, 0x58, 0xa6, 0x61, 0xeb, 0x10, 0xac, 0xbf, 0x61,
	0xd2, 0x2a, 0x40, 0x7f, 0xe0, 0x5e, 0x0d, 0x6f, 0xc7, 0x3d, 0xd7, 0x35, 0xb4, 0x56, 0x07, 0x76,
	0x57, 0x98, 0xd1, 0x12, 0x14, 0x86, 0x97, 0x86, 0x46, 0x75, 0x28, 0x0e, 0x18, 0x1b, 0x32, 0x83,
	0x74, 0x3f, 0x08, 0xe8, 0x37, 0x93, 0x67, 0x7c, 0x98, 0x4f, 0x31, 0xa0, 0x67, 0x50, 0x49, 0xaf,
	0x82, 0xee, 0x64, 0x0b, 0x2c, 0x1d, 0x8f, 0x65, 0xe5, 0x3d, 0xc5, 0x3e, 0xb6, 0x46, 0xef, 0xc0,
	0x58, 0x1a, 0x42, 0xd2, 0xbd, 0xb5, 0x34, 0xac, 0xe6, 0xba, 0xf3, 0xb1, 0x35, 0x87, 0x74, 0xc8,
	0x7d, 0x29, 0x92, 0x1d, 0x7d, 0x05, 0x00, 0x00, 0xff, 0xff, 0xa6, 0x5f, 0xec, 0xc4, 0xea, 0x02,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SchedulerClient is the client API for Scheduler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SchedulerClient interface {
	GetToken(ctx context.Context, in *GetTokenRequest, opts ...grpc.CallOption) (*GetTokenResponse, error)
	// This is inverted cause the server own the service and it sends the request
	// and the client respond.
	DeploymentEvents(ctx context.Context, opts ...grpc.CallOption) (Scheduler_DeploymentEventsClient, error)
}

type schedulerClient struct {
	cc *grpc.ClientConn
}

func NewSchedulerClient(cc *grpc.ClientConn) SchedulerClient {
	return &schedulerClient{cc}
}

func (c *schedulerClient) GetToken(ctx context.Context, in *GetTokenRequest, opts ...grpc.CallOption) (*GetTokenResponse, error) {
	out := new(GetTokenResponse)
	err := c.cc.Invoke(ctx, "/protocol.Scheduler/GetToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerClient) DeploymentEvents(ctx context.Context, opts ...grpc.CallOption) (Scheduler_DeploymentEventsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Scheduler_serviceDesc.Streams[0], "/protocol.Scheduler/DeploymentEvents", opts...)
	if err != nil {
		return nil, err
	}
	x := &schedulerDeploymentEventsClient{stream}
	return x, nil
}

type Scheduler_DeploymentEventsClient interface {
	Send(*DeploymentEventResponse) error
	Recv() (*DeploymentEventRequest, error)
	grpc.ClientStream
}

type schedulerDeploymentEventsClient struct {
	grpc.ClientStream
}

func (x *schedulerDeploymentEventsClient) Send(m *DeploymentEventResponse) error {
	return x.ClientStream.SendMsg(m)
}

func (x *schedulerDeploymentEventsClient) Recv() (*DeploymentEventRequest, error) {
	m := new(DeploymentEventRequest)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SchedulerServer is the server API for Scheduler service.
type SchedulerServer interface {
	GetToken(context.Context, *GetTokenRequest) (*GetTokenResponse, error)
	// This is inverted cause the server own the service and it sends the request
	// and the client respond.
	DeploymentEvents(Scheduler_DeploymentEventsServer) error
}

// UnimplementedSchedulerServer can be embedded to have forward compatible implementations.
type UnimplementedSchedulerServer struct {
}

func (*UnimplementedSchedulerServer) GetToken(ctx context.Context, req *GetTokenRequest) (*GetTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetToken not implemented")
}
func (*UnimplementedSchedulerServer) DeploymentEvents(srv Scheduler_DeploymentEventsServer) error {
	return status.Errorf(codes.Unimplemented, "method DeploymentEvents not implemented")
}

func RegisterSchedulerServer(s *grpc.Server, srv SchedulerServer) {
	s.RegisterService(&_Scheduler_serviceDesc, srv)
}

func _Scheduler_GetToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).GetToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.Scheduler/GetToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).GetToken(ctx, req.(*GetTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scheduler_DeploymentEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SchedulerServer).DeploymentEvents(&schedulerDeploymentEventsServer{stream})
}

type Scheduler_DeploymentEventsServer interface {
	Send(*DeploymentEventRequest) error
	Recv() (*DeploymentEventResponse, error)
	grpc.ServerStream
}

type schedulerDeploymentEventsServer struct {
	grpc.ServerStream
}

func (x *schedulerDeploymentEventsServer) Send(m *DeploymentEventRequest) error {
	return x.ServerStream.SendMsg(m)
}

func (x *schedulerDeploymentEventsServer) Recv() (*DeploymentEventResponse, error) {
	m := new(DeploymentEventResponse)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Scheduler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protocol.Scheduler",
	HandlerType: (*SchedulerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetToken",
			Handler:    _Scheduler_GetToken_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DeploymentEvents",
			Handler:       _Scheduler_DeploymentEvents_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "app.proto",
}
