// Code generated by protoc-gen-go. DO NOT EDIT.
// source: runner.proto

package runnerpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ApplicationStatus int32

const (
	ApplicationStatus_UNKNOWN   ApplicationStatus = 0
	ApplicationStatus_DEPLOYING ApplicationStatus = 1
	ApplicationStatus_RUNNING   ApplicationStatus = 2
	ApplicationStatus_CRASHED   ApplicationStatus = 3
	ApplicationStatus_FAILED    ApplicationStatus = 4
)

var ApplicationStatus_name = map[int32]string{
	0: "UNKNOWN",
	1: "DEPLOYING",
	2: "RUNNING",
	3: "CRASHED",
	4: "FAILED",
}

var ApplicationStatus_value = map[string]int32{
	"UNKNOWN":   0,
	"DEPLOYING": 1,
	"RUNNING":   2,
	"CRASHED":   3,
	"FAILED":    4,
}

func (x ApplicationStatus) String() string {
	return proto.EnumName(ApplicationStatus_name, int32(x))
}

func (ApplicationStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_48eceea7e2abc593, []int{0}
}

type PingRequest struct {
	Time                 int64    `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingRequest) Reset()         { *m = PingRequest{} }
func (m *PingRequest) String() string { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()    {}
func (*PingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_48eceea7e2abc593, []int{0}
}

func (m *PingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingRequest.Unmarshal(m, b)
}
func (m *PingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingRequest.Marshal(b, m, deterministic)
}
func (m *PingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingRequest.Merge(m, src)
}
func (m *PingRequest) XXX_Size() int {
	return xxx_messageInfo_PingRequest.Size(m)
}
func (m *PingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PingRequest proto.InternalMessageInfo

func (m *PingRequest) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type PingResponse struct {
	Time                 int64    `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingResponse) Reset()         { *m = PingResponse{} }
func (m *PingResponse) String() string { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()    {}
func (*PingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_48eceea7e2abc593, []int{1}
}

func (m *PingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingResponse.Unmarshal(m, b)
}
func (m *PingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingResponse.Marshal(b, m, deterministic)
}
func (m *PingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingResponse.Merge(m, src)
}
func (m *PingResponse) XXX_Size() int {
	return xxx_messageInfo_PingResponse.Size(m)
}
func (m *PingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PingResponse proto.InternalMessageInfo

func (m *PingResponse) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type GetConfigurationRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetConfigurationRequest) Reset()         { *m = GetConfigurationRequest{} }
func (m *GetConfigurationRequest) String() string { return proto.CompactTextString(m) }
func (*GetConfigurationRequest) ProtoMessage()    {}
func (*GetConfigurationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_48eceea7e2abc593, []int{2}
}

func (m *GetConfigurationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConfigurationRequest.Unmarshal(m, b)
}
func (m *GetConfigurationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConfigurationRequest.Marshal(b, m, deterministic)
}
func (m *GetConfigurationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConfigurationRequest.Merge(m, src)
}
func (m *GetConfigurationRequest) XXX_Size() int {
	return xxx_messageInfo_GetConfigurationRequest.Size(m)
}
func (m *GetConfigurationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConfigurationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetConfigurationRequest proto.InternalMessageInfo

type GetConfigurationResponse struct {
	ExternalIps          []string `protobuf:"bytes,2,rep,name=externalIps,proto3" json:"externalIps,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetConfigurationResponse) Reset()         { *m = GetConfigurationResponse{} }
func (m *GetConfigurationResponse) String() string { return proto.CompactTextString(m) }
func (*GetConfigurationResponse) ProtoMessage()    {}
func (*GetConfigurationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_48eceea7e2abc593, []int{3}
}

func (m *GetConfigurationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConfigurationResponse.Unmarshal(m, b)
}
func (m *GetConfigurationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConfigurationResponse.Marshal(b, m, deterministic)
}
func (m *GetConfigurationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConfigurationResponse.Merge(m, src)
}
func (m *GetConfigurationResponse) XXX_Size() int {
	return xxx_messageInfo_GetConfigurationResponse.Size(m)
}
func (m *GetConfigurationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConfigurationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetConfigurationResponse proto.InternalMessageInfo

func (m *GetConfigurationResponse) GetExternalIps() []string {
	if m != nil {
		return m.ExternalIps
	}
	return nil
}

type Application struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DeploymentId         string            `protobuf:"bytes,2,opt,name=deploymentId,proto3" json:"deploymentId,omitempty"`
	Name                 string            `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Image                string            `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	Replicas             uint32            `protobuf:"varint,5,opt,name=replicas,proto3" json:"replicas,omitempty"`
	Domains              []string          `protobuf:"bytes,6,rep,name=domains,proto3" json:"domains,omitempty"`
	Environment          map[string]string `protobuf:"bytes,7,rep,name=environment,proto3" json:"environment,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Application) Reset()         { *m = Application{} }
func (m *Application) String() string { return proto.CompactTextString(m) }
func (*Application) ProtoMessage()    {}
func (*Application) Descriptor() ([]byte, []int) {
	return fileDescriptor_48eceea7e2abc593, []int{4}
}

func (m *Application) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Application.Unmarshal(m, b)
}
func (m *Application) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Application.Marshal(b, m, deterministic)
}
func (m *Application) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Application.Merge(m, src)
}
func (m *Application) XXX_Size() int {
	return xxx_messageInfo_Application.Size(m)
}
func (m *Application) XXX_DiscardUnknown() {
	xxx_messageInfo_Application.DiscardUnknown(m)
}

var xxx_messageInfo_Application proto.InternalMessageInfo

func (m *Application) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Application) GetDeploymentId() string {
	if m != nil {
		return m.DeploymentId
	}
	return ""
}

func (m *Application) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Application) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *Application) GetReplicas() uint32 {
	if m != nil {
		return m.Replicas
	}
	return 0
}

func (m *Application) GetDomains() []string {
	if m != nil {
		return m.Domains
	}
	return nil
}

func (m *Application) GetEnvironment() map[string]string {
	if m != nil {
		return m.Environment
	}
	return nil
}

type DeployApplicationRequest struct {
	Application          *Application `protobuf:"bytes,1,opt,name=application,proto3" json:"application,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *DeployApplicationRequest) Reset()         { *m = DeployApplicationRequest{} }
func (m *DeployApplicationRequest) String() string { return proto.CompactTextString(m) }
func (*DeployApplicationRequest) ProtoMessage()    {}
func (*DeployApplicationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_48eceea7e2abc593, []int{5}
}

func (m *DeployApplicationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeployApplicationRequest.Unmarshal(m, b)
}
func (m *DeployApplicationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeployApplicationRequest.Marshal(b, m, deterministic)
}
func (m *DeployApplicationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeployApplicationRequest.Merge(m, src)
}
func (m *DeployApplicationRequest) XXX_Size() int {
	return xxx_messageInfo_DeployApplicationRequest.Size(m)
}
func (m *DeployApplicationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeployApplicationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeployApplicationRequest proto.InternalMessageInfo

func (m *DeployApplicationRequest) GetApplication() *Application {
	if m != nil {
		return m.Application
	}
	return nil
}

type DeployApplicationResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeployApplicationResponse) Reset()         { *m = DeployApplicationResponse{} }
func (m *DeployApplicationResponse) String() string { return proto.CompactTextString(m) }
func (*DeployApplicationResponse) ProtoMessage()    {}
func (*DeployApplicationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_48eceea7e2abc593, []int{6}
}

func (m *DeployApplicationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeployApplicationResponse.Unmarshal(m, b)
}
func (m *DeployApplicationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeployApplicationResponse.Marshal(b, m, deterministic)
}
func (m *DeployApplicationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeployApplicationResponse.Merge(m, src)
}
func (m *DeployApplicationResponse) XXX_Size() int {
	return xxx_messageInfo_DeployApplicationResponse.Size(m)
}
func (m *DeployApplicationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeployApplicationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeployApplicationResponse proto.InternalMessageInfo

type DeleteApplicationRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteApplicationRequest) Reset()         { *m = DeleteApplicationRequest{} }
func (m *DeleteApplicationRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteApplicationRequest) ProtoMessage()    {}
func (*DeleteApplicationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_48eceea7e2abc593, []int{7}
}

func (m *DeleteApplicationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteApplicationRequest.Unmarshal(m, b)
}
func (m *DeleteApplicationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteApplicationRequest.Marshal(b, m, deterministic)
}
func (m *DeleteApplicationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteApplicationRequest.Merge(m, src)
}
func (m *DeleteApplicationRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteApplicationRequest.Size(m)
}
func (m *DeleteApplicationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteApplicationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteApplicationRequest proto.InternalMessageInfo

func (m *DeleteApplicationRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DeleteApplicationRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DeleteApplicationResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteApplicationResponse) Reset()         { *m = DeleteApplicationResponse{} }
func (m *DeleteApplicationResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteApplicationResponse) ProtoMessage()    {}
func (*DeleteApplicationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_48eceea7e2abc593, []int{8}
}

func (m *DeleteApplicationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteApplicationResponse.Unmarshal(m, b)
}
func (m *DeleteApplicationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteApplicationResponse.Marshal(b, m, deterministic)
}
func (m *DeleteApplicationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteApplicationResponse.Merge(m, src)
}
func (m *DeleteApplicationResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteApplicationResponse.Size(m)
}
func (m *DeleteApplicationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteApplicationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteApplicationResponse proto.InternalMessageInfo

type GetApplicationLogsRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetApplicationLogsRequest) Reset()         { *m = GetApplicationLogsRequest{} }
func (m *GetApplicationLogsRequest) String() string { return proto.CompactTextString(m) }
func (*GetApplicationLogsRequest) ProtoMessage()    {}
func (*GetApplicationLogsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_48eceea7e2abc593, []int{9}
}

func (m *GetApplicationLogsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetApplicationLogsRequest.Unmarshal(m, b)
}
func (m *GetApplicationLogsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetApplicationLogsRequest.Marshal(b, m, deterministic)
}
func (m *GetApplicationLogsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetApplicationLogsRequest.Merge(m, src)
}
func (m *GetApplicationLogsRequest) XXX_Size() int {
	return xxx_messageInfo_GetApplicationLogsRequest.Size(m)
}
func (m *GetApplicationLogsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetApplicationLogsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetApplicationLogsRequest proto.InternalMessageInfo

func (m *GetApplicationLogsRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetApplicationLogsRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetApplicationLogsResponse struct {
	Time                 string   `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Pod                  string   `protobuf:"bytes,2,opt,name=pod,proto3" json:"pod,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetApplicationLogsResponse) Reset()         { *m = GetApplicationLogsResponse{} }
func (m *GetApplicationLogsResponse) String() string { return proto.CompactTextString(m) }
func (*GetApplicationLogsResponse) ProtoMessage()    {}
func (*GetApplicationLogsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_48eceea7e2abc593, []int{10}
}

func (m *GetApplicationLogsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetApplicationLogsResponse.Unmarshal(m, b)
}
func (m *GetApplicationLogsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetApplicationLogsResponse.Marshal(b, m, deterministic)
}
func (m *GetApplicationLogsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetApplicationLogsResponse.Merge(m, src)
}
func (m *GetApplicationLogsResponse) XXX_Size() int {
	return xxx_messageInfo_GetApplicationLogsResponse.Size(m)
}
func (m *GetApplicationLogsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetApplicationLogsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetApplicationLogsResponse proto.InternalMessageInfo

func (m *GetApplicationLogsResponse) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *GetApplicationLogsResponse) GetPod() string {
	if m != nil {
		return m.Pod
	}
	return ""
}

func (m *GetApplicationLogsResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GetApplicationStatusRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DeploymentId         string   `protobuf:"bytes,2,opt,name=deploymentId,proto3" json:"deploymentId,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetApplicationStatusRequest) Reset()         { *m = GetApplicationStatusRequest{} }
func (m *GetApplicationStatusRequest) String() string { return proto.CompactTextString(m) }
func (*GetApplicationStatusRequest) ProtoMessage()    {}
func (*GetApplicationStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_48eceea7e2abc593, []int{11}
}

func (m *GetApplicationStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetApplicationStatusRequest.Unmarshal(m, b)
}
func (m *GetApplicationStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetApplicationStatusRequest.Marshal(b, m, deterministic)
}
func (m *GetApplicationStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetApplicationStatusRequest.Merge(m, src)
}
func (m *GetApplicationStatusRequest) XXX_Size() int {
	return xxx_messageInfo_GetApplicationStatusRequest.Size(m)
}
func (m *GetApplicationStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetApplicationStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetApplicationStatusRequest proto.InternalMessageInfo

func (m *GetApplicationStatusRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetApplicationStatusRequest) GetDeploymentId() string {
	if m != nil {
		return m.DeploymentId
	}
	return ""
}

func (m *GetApplicationStatusRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetApplicationStatusResponse struct {
	Status               ApplicationStatus `protobuf:"varint,1,opt,name=status,proto3,enum=runnerpb.ApplicationStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetApplicationStatusResponse) Reset()         { *m = GetApplicationStatusResponse{} }
func (m *GetApplicationStatusResponse) String() string { return proto.CompactTextString(m) }
func (*GetApplicationStatusResponse) ProtoMessage()    {}
func (*GetApplicationStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_48eceea7e2abc593, []int{12}
}

func (m *GetApplicationStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetApplicationStatusResponse.Unmarshal(m, b)
}
func (m *GetApplicationStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetApplicationStatusResponse.Marshal(b, m, deterministic)
}
func (m *GetApplicationStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetApplicationStatusResponse.Merge(m, src)
}
func (m *GetApplicationStatusResponse) XXX_Size() int {
	return xxx_messageInfo_GetApplicationStatusResponse.Size(m)
}
func (m *GetApplicationStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetApplicationStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetApplicationStatusResponse proto.InternalMessageInfo

func (m *GetApplicationStatusResponse) GetStatus() ApplicationStatus {
	if m != nil {
		return m.Status
	}
	return ApplicationStatus_UNKNOWN
}

func init() {
	proto.RegisterEnum("runnerpb.ApplicationStatus", ApplicationStatus_name, ApplicationStatus_value)
	proto.RegisterType((*PingRequest)(nil), "runnerpb.PingRequest")
	proto.RegisterType((*PingResponse)(nil), "runnerpb.PingResponse")
	proto.RegisterType((*GetConfigurationRequest)(nil), "runnerpb.GetConfigurationRequest")
	proto.RegisterType((*GetConfigurationResponse)(nil), "runnerpb.GetConfigurationResponse")
	proto.RegisterType((*Application)(nil), "runnerpb.Application")
	proto.RegisterMapType((map[string]string)(nil), "runnerpb.Application.EnvironmentEntry")
	proto.RegisterType((*DeployApplicationRequest)(nil), "runnerpb.DeployApplicationRequest")
	proto.RegisterType((*DeployApplicationResponse)(nil), "runnerpb.DeployApplicationResponse")
	proto.RegisterType((*DeleteApplicationRequest)(nil), "runnerpb.DeleteApplicationRequest")
	proto.RegisterType((*DeleteApplicationResponse)(nil), "runnerpb.DeleteApplicationResponse")
	proto.RegisterType((*GetApplicationLogsRequest)(nil), "runnerpb.GetApplicationLogsRequest")
	proto.RegisterType((*GetApplicationLogsResponse)(nil), "runnerpb.GetApplicationLogsResponse")
	proto.RegisterType((*GetApplicationStatusRequest)(nil), "runnerpb.GetApplicationStatusRequest")
	proto.RegisterType((*GetApplicationStatusResponse)(nil), "runnerpb.GetApplicationStatusResponse")
}

func init() { proto.RegisterFile("runner.proto", fileDescriptor_48eceea7e2abc593) }

var fileDescriptor_48eceea7e2abc593 = []byte{
	// 623 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0x51, 0x6f, 0xda, 0x3c,
	0x14, 0x6d, 0x12, 0x0a, 0xe5, 0x86, 0x56, 0xa9, 0xd5, 0xef, 0x5b, 0x08, 0x7b, 0xa0, 0xee, 0x56,
	0xa1, 0x3d, 0xa0, 0x89, 0x3e, 0x74, 0x9a, 0xa6, 0x4e, 0xa8, 0x30, 0x8a, 0x86, 0xd2, 0x2a, 0x08,
	0x4d, 0xd3, 0xa6, 0x49, 0x69, 0xf1, 0x50, 0x34, 0xe2, 0x64, 0x89, 0xa9, 0xc6, 0x6f, 0xda, 0x7e,
	0xe4, 0x64, 0x27, 0x81, 0x04, 0x12, 0xa6, 0xed, 0xcd, 0xd7, 0xf7, 0xdc, 0x73, 0xae, 0x73, 0x8f,
	0x1d, 0xa8, 0x05, 0x0b, 0x4a, 0x49, 0xd0, 0xf6, 0x03, 0x8f, 0x79, 0xe8, 0x20, 0x8a, 0xfc, 0x7b,
	0x7c, 0x0a, 0xea, 0x9d, 0x43, 0x67, 0x16, 0xf9, 0xbe, 0x20, 0x21, 0x43, 0x08, 0x4a, 0xcc, 0x71,
	0x89, 0x2e, 0x35, 0xa5, 0x96, 0x62, 0x89, 0x35, 0xc6, 0x50, 0x8b, 0x20, 0xa1, 0xef, 0xd1, 0x90,
	0xe4, 0x62, 0xea, 0xf0, 0x64, 0x40, 0xd8, 0xb5, 0x47, 0xbf, 0x3a, 0xb3, 0x45, 0x60, 0x33, 0xc7,
	0xa3, 0x31, 0x25, 0x7e, 0x03, 0xfa, 0x76, 0x2a, 0xa6, 0x6a, 0x82, 0x4a, 0x7e, 0x30, 0x12, 0x50,
	0x7b, 0x3e, 0xf4, 0x43, 0x5d, 0x6e, 0x2a, 0xad, 0xaa, 0x95, 0xde, 0xc2, 0x3f, 0x65, 0x50, 0xbb,
	0xbe, 0x3f, 0x77, 0x1e, 0x44, 0x25, 0x3a, 0x02, 0xd9, 0x99, 0x0a, 0xe9, 0xaa, 0x25, 0x3b, 0x53,
	0x84, 0xa1, 0x36, 0x25, 0xfe, 0xdc, 0x5b, 0xba, 0x84, 0xb2, 0xe1, 0x54, 0x97, 0x45, 0x26, 0xb3,
	0xc7, 0x1b, 0xa6, 0xb6, 0x4b, 0x74, 0x45, 0xe4, 0xc4, 0x1a, 0x9d, 0xc0, 0xbe, 0xe3, 0xda, 0x33,
	0xa2, 0x97, 0xc4, 0x66, 0x14, 0x20, 0x03, 0x0e, 0x02, 0x22, 0xc4, 0x42, 0x7d, 0xbf, 0x29, 0xb5,
	0x0e, 0xad, 0x55, 0x8c, 0x74, 0xa8, 0x4c, 0x3d, 0xd7, 0x76, 0x68, 0xa8, 0x97, 0x45, 0x9f, 0x49,
	0x88, 0x6e, 0x40, 0x25, 0xf4, 0xd1, 0x09, 0x3c, 0xca, 0x05, 0xf5, 0x4a, 0x53, 0x69, 0xa9, 0x9d,
	0xf3, 0x76, 0xf2, 0x8d, 0xdb, 0xa9, 0xfe, 0xdb, 0xfd, 0x35, 0xb0, 0x4f, 0x59, 0xb0, 0xb4, 0xd2,
	0xa5, 0xc6, 0x15, 0x68, 0x9b, 0x00, 0xa4, 0x81, 0xf2, 0x8d, 0x2c, 0xe3, 0x23, 0xf3, 0x25, 0xef,
	0xfd, 0xd1, 0x9e, 0x2f, 0x48, 0x7c, 0xd8, 0x28, 0x78, 0x2d, 0xbf, 0x92, 0xf0, 0x18, 0xf4, 0x9e,
	0x38, 0x79, 0x4a, 0x32, 0x19, 0xed, 0x25, 0xa8, 0xf6, 0x7a, 0x57, 0xf0, 0xa9, 0x9d, 0xff, 0x72,
	0xbb, 0xb4, 0xd2, 0x48, 0xdc, 0x80, 0x7a, 0x0e, 0x69, 0x34, 0x41, 0x7c, 0xc5, 0x15, 0xe7, 0x84,
	0x91, 0x1c, 0xc5, 0xcd, 0x59, 0x25, 0x73, 0x90, 0xd7, 0x73, 0x88, 0xc8, 0xb7, 0xea, 0x63, 0xf2,
	0xb7, 0x50, 0x1f, 0x10, 0x96, 0xca, 0x8c, 0xbc, 0x59, 0xf8, 0x37, 0xec, 0x9f, 0xc1, 0xc8, 0x23,
	0xc8, 0x31, 0x72, 0x35, 0x32, 0x32, 0xff, 0xda, 0xbe, 0x97, 0xd8, 0x88, 0x2f, 0xf9, 0xdc, 0x5d,
	0x12, 0x86, 0xdc, 0x2b, 0x91, 0x81, 0x92, 0x10, 0x13, 0x68, 0x64, 0xd9, 0xc7, 0xcc, 0x66, 0x8b,
	0xc2, 0x06, 0xff, 0xd1, 0xaa, 0x78, 0x0c, 0x4f, 0xf3, 0x65, 0xe2, 0x63, 0x5c, 0x40, 0x39, 0x14,
	0x3b, 0x42, 0xeb, 0xa8, 0xd3, 0xc8, 0x9d, 0x69, 0x5c, 0x14, 0x43, 0x5f, 0x4c, 0xe0, 0x78, 0x2b,
	0x89, 0x54, 0xa8, 0x4c, 0xcc, 0xf7, 0xe6, 0xed, 0x07, 0x53, 0xdb, 0x43, 0x87, 0x50, 0xed, 0xf5,
	0xef, 0x46, 0xb7, 0x1f, 0x87, 0xe6, 0x40, 0x93, 0x78, 0xce, 0x9a, 0x98, 0x26, 0x0f, 0x64, 0x1e,
	0x5c, 0x5b, 0xdd, 0xf1, 0x4d, 0xbf, 0xa7, 0x29, 0x08, 0xa0, 0xfc, 0xae, 0x3b, 0x1c, 0xf5, 0x7b,
	0x5a, 0xa9, 0xf3, 0xab, 0x04, 0x65, 0x4b, 0xa8, 0xa3, 0x4b, 0x28, 0xf1, 0x67, 0x03, 0xa5, 0x2c,
	0x96, 0x7a, 0x69, 0x8c, 0xff, 0x37, 0xb7, 0xe3, 0x99, 0xef, 0xa1, 0x4f, 0xa0, 0x6d, 0x3e, 0x18,
	0xe8, 0x74, 0x8d, 0x2e, 0x78, 0x67, 0x0c, 0xbc, 0x0b, 0xb2, 0x22, 0xff, 0x02, 0xc7, 0x5b, 0x66,
	0x46, 0xa9, 0xd2, 0xa2, 0xeb, 0x63, 0x9c, 0xed, 0xc4, 0x64, 0xf9, 0x37, 0xfc, 0x9c, 0xe5, 0xcf,
	0xbf, 0x2c, 0x59, 0xfe, 0xa2, 0x0b, 0xb1, 0x87, 0x66, 0x70, 0x92, 0x67, 0x06, 0xf4, 0x3c, 0x73,
	0xfa, 0x22, 0x4f, 0x1a, 0xe7, 0x7f, 0x82, 0xad, 0x84, 0x1e, 0x00, 0x6d, 0x5f, 0x1d, 0x74, 0x56,
	0x54, 0x9f, 0xba, 0x99, 0xc6, 0xb3, 0xdd, 0xa0, 0x44, 0xe2, 0xa5, 0x74, 0x5f, 0x16, 0xbf, 0xa3,
	0x8b, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe0, 0x64, 0xac, 0x37, 0x9e, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RunnerClient is the client API for Runner service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RunnerClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	GetConfiguration(ctx context.Context, in *GetConfigurationRequest, opts ...grpc.CallOption) (*GetConfigurationResponse, error)
	DeployApplication(ctx context.Context, in *DeployApplicationRequest, opts ...grpc.CallOption) (*DeployApplicationResponse, error)
	DeleteApplication(ctx context.Context, in *DeleteApplicationRequest, opts ...grpc.CallOption) (*DeleteApplicationResponse, error)
	GetApplicationStatus(ctx context.Context, in *GetApplicationStatusRequest, opts ...grpc.CallOption) (*GetApplicationStatusResponse, error)
	GetApplicationLogs(ctx context.Context, in *GetApplicationLogsRequest, opts ...grpc.CallOption) (Runner_GetApplicationLogsClient, error)
}

type runnerClient struct {
	cc *grpc.ClientConn
}

func NewRunnerClient(cc *grpc.ClientConn) RunnerClient {
	return &runnerClient{cc}
}

func (c *runnerClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, "/runnerpb.Runner/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerClient) GetConfiguration(ctx context.Context, in *GetConfigurationRequest, opts ...grpc.CallOption) (*GetConfigurationResponse, error) {
	out := new(GetConfigurationResponse)
	err := c.cc.Invoke(ctx, "/runnerpb.Runner/GetConfiguration", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerClient) DeployApplication(ctx context.Context, in *DeployApplicationRequest, opts ...grpc.CallOption) (*DeployApplicationResponse, error) {
	out := new(DeployApplicationResponse)
	err := c.cc.Invoke(ctx, "/runnerpb.Runner/DeployApplication", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerClient) DeleteApplication(ctx context.Context, in *DeleteApplicationRequest, opts ...grpc.CallOption) (*DeleteApplicationResponse, error) {
	out := new(DeleteApplicationResponse)
	err := c.cc.Invoke(ctx, "/runnerpb.Runner/DeleteApplication", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerClient) GetApplicationStatus(ctx context.Context, in *GetApplicationStatusRequest, opts ...grpc.CallOption) (*GetApplicationStatusResponse, error) {
	out := new(GetApplicationStatusResponse)
	err := c.cc.Invoke(ctx, "/runnerpb.Runner/GetApplicationStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerClient) GetApplicationLogs(ctx context.Context, in *GetApplicationLogsRequest, opts ...grpc.CallOption) (Runner_GetApplicationLogsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Runner_serviceDesc.Streams[0], "/runnerpb.Runner/GetApplicationLogs", opts...)
	if err != nil {
		return nil, err
	}
	x := &runnerGetApplicationLogsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Runner_GetApplicationLogsClient interface {
	Recv() (*GetApplicationLogsResponse, error)
	grpc.ClientStream
}

type runnerGetApplicationLogsClient struct {
	grpc.ClientStream
}

func (x *runnerGetApplicationLogsClient) Recv() (*GetApplicationLogsResponse, error) {
	m := new(GetApplicationLogsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RunnerServer is the server API for Runner service.
type RunnerServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	GetConfiguration(context.Context, *GetConfigurationRequest) (*GetConfigurationResponse, error)
	DeployApplication(context.Context, *DeployApplicationRequest) (*DeployApplicationResponse, error)
	DeleteApplication(context.Context, *DeleteApplicationRequest) (*DeleteApplicationResponse, error)
	GetApplicationStatus(context.Context, *GetApplicationStatusRequest) (*GetApplicationStatusResponse, error)
	GetApplicationLogs(*GetApplicationLogsRequest, Runner_GetApplicationLogsServer) error
}

// UnimplementedRunnerServer can be embedded to have forward compatible implementations.
type UnimplementedRunnerServer struct {
}

func (*UnimplementedRunnerServer) Ping(ctx context.Context, req *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (*UnimplementedRunnerServer) GetConfiguration(ctx context.Context, req *GetConfigurationRequest) (*GetConfigurationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConfiguration not implemented")
}
func (*UnimplementedRunnerServer) DeployApplication(ctx context.Context, req *DeployApplicationRequest) (*DeployApplicationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeployApplication not implemented")
}
func (*UnimplementedRunnerServer) DeleteApplication(ctx context.Context, req *DeleteApplicationRequest) (*DeleteApplicationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteApplication not implemented")
}
func (*UnimplementedRunnerServer) GetApplicationStatus(ctx context.Context, req *GetApplicationStatusRequest) (*GetApplicationStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetApplicationStatus not implemented")
}
func (*UnimplementedRunnerServer) GetApplicationLogs(req *GetApplicationLogsRequest, srv Runner_GetApplicationLogsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetApplicationLogs not implemented")
}

func RegisterRunnerServer(s *grpc.Server, srv RunnerServer) {
	s.RegisterService(&_Runner_serviceDesc, srv)
}

func _Runner_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/runnerpb.Runner/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runner_GetConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigurationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServer).GetConfiguration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/runnerpb.Runner/GetConfiguration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServer).GetConfiguration(ctx, req.(*GetConfigurationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runner_DeployApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeployApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServer).DeployApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/runnerpb.Runner/DeployApplication",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServer).DeployApplication(ctx, req.(*DeployApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runner_DeleteApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServer).DeleteApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/runnerpb.Runner/DeleteApplication",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServer).DeleteApplication(ctx, req.(*DeleteApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runner_GetApplicationStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetApplicationStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServer).GetApplicationStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/runnerpb.Runner/GetApplicationStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServer).GetApplicationStatus(ctx, req.(*GetApplicationStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runner_GetApplicationLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetApplicationLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RunnerServer).GetApplicationLogs(m, &runnerGetApplicationLogsServer{stream})
}

type Runner_GetApplicationLogsServer interface {
	Send(*GetApplicationLogsResponse) error
	grpc.ServerStream
}

type runnerGetApplicationLogsServer struct {
	grpc.ServerStream
}

func (x *runnerGetApplicationLogsServer) Send(m *GetApplicationLogsResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _Runner_serviceDesc = grpc.ServiceDesc{
	ServiceName: "runnerpb.Runner",
	HandlerType: (*RunnerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Runner_Ping_Handler,
		},
		{
			MethodName: "GetConfiguration",
			Handler:    _Runner_GetConfiguration_Handler,
		},
		{
			MethodName: "DeployApplication",
			Handler:    _Runner_DeployApplication_Handler,
		},
		{
			MethodName: "DeleteApplication",
			Handler:    _Runner_DeleteApplication_Handler,
		},
		{
			MethodName: "GetApplicationStatus",
			Handler:    _Runner_GetApplicationStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetApplicationLogs",
			Handler:       _Runner_GetApplicationLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "runner.proto",
}
