export const FETCH_APPLICATION_PENDING = 'FETCH_APPLICATION_PENDING';
export const FETCH_APPLICATION_SUCCESS = 'FETCH_APPLICATION_SUCCESS';
export const FETCH_APPLICATION_ERROR = 'FETCH_APPLICATION_ERROR';

export const DEPLOY_APPLICATION_PENDING = 'DEPLOY_APPLICATION_PENDING';

export const UPDATE_APPLICATION_PENDING = 'UPDATE_APPLICATION_PENDING';

export const DELETE_APPLICATION_PENDING = 'DELETE_APPLICATION_PENDING';
