// Code generated by protoc-gen-go. DO NOT EDIT.
// source: runner.proto

package protocol

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RunnerType int32

const (
	RunnerType_DOCKER_SWARM RunnerType = 0
	RunnerType_KUBERNETES   RunnerType = 1
)

var RunnerType_name = map[int32]string{
	0: "DOCKER_SWARM",
	1: "KUBERNETES",
}

var RunnerType_value = map[string]int32{
	"DOCKER_SWARM": 0,
	"KUBERNETES":   1,
}

func (x RunnerType) String() string {
	return proto.EnumName(RunnerType_name, int32(x))
}

func (RunnerType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_48eceea7e2abc593, []int{0}
}

type ApplicationState int32

const (
	ApplicationState_UNKNOWN  ApplicationState = 0
	ApplicationState_STOPPED  ApplicationState = 1
	ApplicationState_STARTING ApplicationState = 2
	ApplicationState_RUNNING  ApplicationState = 3
)

var ApplicationState_name = map[int32]string{
	0: "UNKNOWN",
	1: "STOPPED",
	2: "STARTING",
	3: "RUNNING",
}

var ApplicationState_value = map[string]int32{
	"UNKNOWN":  0,
	"STOPPED":  1,
	"STARTING": 2,
	"RUNNING":  3,
}

func (x ApplicationState) String() string {
	return proto.EnumName(ApplicationState_name, int32(x))
}

func (ApplicationState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_48eceea7e2abc593, []int{1}
}

type GetApplicationLogsResponse_Output int32

const (
	GetApplicationLogsResponse_STDOUT GetApplicationLogsResponse_Output = 0
	GetApplicationLogsResponse_STDERR GetApplicationLogsResponse_Output = 1
)

var GetApplicationLogsResponse_Output_name = map[int32]string{
	0: "STDOUT",
	1: "STDERR",
}

var GetApplicationLogsResponse_Output_value = map[string]int32{
	"STDOUT": 0,
	"STDERR": 1,
}

func (x GetApplicationLogsResponse_Output) String() string {
	return proto.EnumName(GetApplicationLogsResponse_Output_name, int32(x))
}

func (GetApplicationLogsResponse_Output) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_48eceea7e2abc593, []int{8, 0}
}

type GetConfigurationRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetConfigurationRequest) Reset()         { *m = GetConfigurationRequest{} }
func (m *GetConfigurationRequest) String() string { return proto.CompactTextString(m) }
func (*GetConfigurationRequest) ProtoMessage()    {}
func (*GetConfigurationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_48eceea7e2abc593, []int{0}
}

func (m *GetConfigurationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConfigurationRequest.Unmarshal(m, b)
}
func (m *GetConfigurationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConfigurationRequest.Marshal(b, m, deterministic)
}
func (m *GetConfigurationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConfigurationRequest.Merge(m, src)
}
func (m *GetConfigurationRequest) XXX_Size() int {
	return xxx_messageInfo_GetConfigurationRequest.Size(m)
}
func (m *GetConfigurationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConfigurationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetConfigurationRequest proto.InternalMessageInfo

type GetConfigurationResponse struct {
	Type                 RunnerType `protobuf:"varint,1,opt,name=type,proto3,enum=protocol.RunnerType" json:"type,omitempty"`
	ExternalIps          []string   `protobuf:"bytes,2,rep,name=externalIps,proto3" json:"externalIps,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetConfigurationResponse) Reset()         { *m = GetConfigurationResponse{} }
func (m *GetConfigurationResponse) String() string { return proto.CompactTextString(m) }
func (*GetConfigurationResponse) ProtoMessage()    {}
func (*GetConfigurationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_48eceea7e2abc593, []int{1}
}

func (m *GetConfigurationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConfigurationResponse.Unmarshal(m, b)
}
func (m *GetConfigurationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConfigurationResponse.Marshal(b, m, deterministic)
}
func (m *GetConfigurationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConfigurationResponse.Merge(m, src)
}
func (m *GetConfigurationResponse) XXX_Size() int {
	return xxx_messageInfo_GetConfigurationResponse.Size(m)
}
func (m *GetConfigurationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConfigurationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetConfigurationResponse proto.InternalMessageInfo

func (m *GetConfigurationResponse) GetType() RunnerType {
	if m != nil {
		return m.Type
	}
	return RunnerType_DOCKER_SWARM
}

func (m *GetConfigurationResponse) GetExternalIps() []string {
	if m != nil {
		return m.ExternalIps
	}
	return nil
}

type Application struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DeploymentId         string            `protobuf:"bytes,2,opt,name=deploymentId,proto3" json:"deploymentId,omitempty"`
	Name                 string            `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Image                string            `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	Replicas             uint32            `protobuf:"varint,5,opt,name=replicas,proto3" json:"replicas,omitempty"`
	Domains              []string          `protobuf:"bytes,6,rep,name=domains,proto3" json:"domains,omitempty"`
	Environment          map[string]string `protobuf:"bytes,7,rep,name=environment,proto3" json:"environment,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Application) Reset()         { *m = Application{} }
func (m *Application) String() string { return proto.CompactTextString(m) }
func (*Application) ProtoMessage()    {}
func (*Application) Descriptor() ([]byte, []int) {
	return fileDescriptor_48eceea7e2abc593, []int{2}
}

func (m *Application) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Application.Unmarshal(m, b)
}
func (m *Application) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Application.Marshal(b, m, deterministic)
}
func (m *Application) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Application.Merge(m, src)
}
func (m *Application) XXX_Size() int {
	return xxx_messageInfo_Application.Size(m)
}
func (m *Application) XXX_DiscardUnknown() {
	xxx_messageInfo_Application.DiscardUnknown(m)
}

var xxx_messageInfo_Application proto.InternalMessageInfo

func (m *Application) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Application) GetDeploymentId() string {
	if m != nil {
		return m.DeploymentId
	}
	return ""
}

func (m *Application) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Application) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *Application) GetReplicas() uint32 {
	if m != nil {
		return m.Replicas
	}
	return 0
}

func (m *Application) GetDomains() []string {
	if m != nil {
		return m.Domains
	}
	return nil
}

func (m *Application) GetEnvironment() map[string]string {
	if m != nil {
		return m.Environment
	}
	return nil
}

type DeployApplicationRequest struct {
	Application          *Application `protobuf:"bytes,1,opt,name=application,proto3" json:"application,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *DeployApplicationRequest) Reset()         { *m = DeployApplicationRequest{} }
func (m *DeployApplicationRequest) String() string { return proto.CompactTextString(m) }
func (*DeployApplicationRequest) ProtoMessage()    {}
func (*DeployApplicationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_48eceea7e2abc593, []int{3}
}

func (m *DeployApplicationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeployApplicationRequest.Unmarshal(m, b)
}
func (m *DeployApplicationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeployApplicationRequest.Marshal(b, m, deterministic)
}
func (m *DeployApplicationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeployApplicationRequest.Merge(m, src)
}
func (m *DeployApplicationRequest) XXX_Size() int {
	return xxx_messageInfo_DeployApplicationRequest.Size(m)
}
func (m *DeployApplicationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeployApplicationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeployApplicationRequest proto.InternalMessageInfo

func (m *DeployApplicationRequest) GetApplication() *Application {
	if m != nil {
		return m.Application
	}
	return nil
}

type DeployApplicationResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeployApplicationResponse) Reset()         { *m = DeployApplicationResponse{} }
func (m *DeployApplicationResponse) String() string { return proto.CompactTextString(m) }
func (*DeployApplicationResponse) ProtoMessage()    {}
func (*DeployApplicationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_48eceea7e2abc593, []int{4}
}

func (m *DeployApplicationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeployApplicationResponse.Unmarshal(m, b)
}
func (m *DeployApplicationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeployApplicationResponse.Marshal(b, m, deterministic)
}
func (m *DeployApplicationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeployApplicationResponse.Merge(m, src)
}
func (m *DeployApplicationResponse) XXX_Size() int {
	return xxx_messageInfo_DeployApplicationResponse.Size(m)
}
func (m *DeployApplicationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeployApplicationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeployApplicationResponse proto.InternalMessageInfo

type DeleteApplicationRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteApplicationRequest) Reset()         { *m = DeleteApplicationRequest{} }
func (m *DeleteApplicationRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteApplicationRequest) ProtoMessage()    {}
func (*DeleteApplicationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_48eceea7e2abc593, []int{5}
}

func (m *DeleteApplicationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteApplicationRequest.Unmarshal(m, b)
}
func (m *DeleteApplicationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteApplicationRequest.Marshal(b, m, deterministic)
}
func (m *DeleteApplicationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteApplicationRequest.Merge(m, src)
}
func (m *DeleteApplicationRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteApplicationRequest.Size(m)
}
func (m *DeleteApplicationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteApplicationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteApplicationRequest proto.InternalMessageInfo

func (m *DeleteApplicationRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteApplicationResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteApplicationResponse) Reset()         { *m = DeleteApplicationResponse{} }
func (m *DeleteApplicationResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteApplicationResponse) ProtoMessage()    {}
func (*DeleteApplicationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_48eceea7e2abc593, []int{6}
}

func (m *DeleteApplicationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteApplicationResponse.Unmarshal(m, b)
}
func (m *DeleteApplicationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteApplicationResponse.Marshal(b, m, deterministic)
}
func (m *DeleteApplicationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteApplicationResponse.Merge(m, src)
}
func (m *DeleteApplicationResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteApplicationResponse.Size(m)
}
func (m *DeleteApplicationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteApplicationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteApplicationResponse proto.InternalMessageInfo

type GetApplicationLogsRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetApplicationLogsRequest) Reset()         { *m = GetApplicationLogsRequest{} }
func (m *GetApplicationLogsRequest) String() string { return proto.CompactTextString(m) }
func (*GetApplicationLogsRequest) ProtoMessage()    {}
func (*GetApplicationLogsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_48eceea7e2abc593, []int{7}
}

func (m *GetApplicationLogsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetApplicationLogsRequest.Unmarshal(m, b)
}
func (m *GetApplicationLogsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetApplicationLogsRequest.Marshal(b, m, deterministic)
}
func (m *GetApplicationLogsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetApplicationLogsRequest.Merge(m, src)
}
func (m *GetApplicationLogsRequest) XXX_Size() int {
	return xxx_messageInfo_GetApplicationLogsRequest.Size(m)
}
func (m *GetApplicationLogsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetApplicationLogsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetApplicationLogsRequest proto.InternalMessageInfo

func (m *GetApplicationLogsRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetApplicationLogsResponse struct {
	Output               GetApplicationLogsResponse_Output `protobuf:"varint,1,opt,name=output,proto3,enum=protocol.GetApplicationLogsResponse_Output" json:"output,omitempty"`
	Time                 string                            `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	TaskId               string                            `protobuf:"bytes,3,opt,name=taskId,proto3" json:"taskId,omitempty"`
	Message              string                            `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *GetApplicationLogsResponse) Reset()         { *m = GetApplicationLogsResponse{} }
func (m *GetApplicationLogsResponse) String() string { return proto.CompactTextString(m) }
func (*GetApplicationLogsResponse) ProtoMessage()    {}
func (*GetApplicationLogsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_48eceea7e2abc593, []int{8}
}

func (m *GetApplicationLogsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetApplicationLogsResponse.Unmarshal(m, b)
}
func (m *GetApplicationLogsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetApplicationLogsResponse.Marshal(b, m, deterministic)
}
func (m *GetApplicationLogsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetApplicationLogsResponse.Merge(m, src)
}
func (m *GetApplicationLogsResponse) XXX_Size() int {
	return xxx_messageInfo_GetApplicationLogsResponse.Size(m)
}
func (m *GetApplicationLogsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetApplicationLogsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetApplicationLogsResponse proto.InternalMessageInfo

func (m *GetApplicationLogsResponse) GetOutput() GetApplicationLogsResponse_Output {
	if m != nil {
		return m.Output
	}
	return GetApplicationLogsResponse_STDOUT
}

func (m *GetApplicationLogsResponse) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *GetApplicationLogsResponse) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func (m *GetApplicationLogsResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterEnum("protocol.RunnerType", RunnerType_name, RunnerType_value)
	proto.RegisterEnum("protocol.ApplicationState", ApplicationState_name, ApplicationState_value)
	proto.RegisterEnum("protocol.GetApplicationLogsResponse_Output", GetApplicationLogsResponse_Output_name, GetApplicationLogsResponse_Output_value)
	proto.RegisterType((*GetConfigurationRequest)(nil), "protocol.GetConfigurationRequest")
	proto.RegisterType((*GetConfigurationResponse)(nil), "protocol.GetConfigurationResponse")
	proto.RegisterType((*Application)(nil), "protocol.Application")
	proto.RegisterMapType((map[string]string)(nil), "protocol.Application.EnvironmentEntry")
	proto.RegisterType((*DeployApplicationRequest)(nil), "protocol.DeployApplicationRequest")
	proto.RegisterType((*DeployApplicationResponse)(nil), "protocol.DeployApplicationResponse")
	proto.RegisterType((*DeleteApplicationRequest)(nil), "protocol.DeleteApplicationRequest")
	proto.RegisterType((*DeleteApplicationResponse)(nil), "protocol.DeleteApplicationResponse")
	proto.RegisterType((*GetApplicationLogsRequest)(nil), "protocol.GetApplicationLogsRequest")
	proto.RegisterType((*GetApplicationLogsResponse)(nil), "protocol.GetApplicationLogsResponse")
}

func init() { proto.RegisterFile("runner.proto", fileDescriptor_48eceea7e2abc593) }

var fileDescriptor_48eceea7e2abc593 = []byte{
	// 615 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x51, 0x6f, 0xd3, 0x3c,
	0x14, 0x6d, 0xd2, 0x2d, 0xdb, 0x6e, 0xfa, 0x4d, 0xfe, 0xae, 0x06, 0x64, 0xe5, 0xa5, 0x64, 0x08,
	0x55, 0x9b, 0x54, 0xa1, 0xf2, 0x00, 0xe2, 0x01, 0x69, 0xac, 0x51, 0xa9, 0x06, 0xe9, 0xe4, 0xa4,
	0xda, 0x03, 0x12, 0x28, 0xac, 0xde, 0x14, 0xad, 0x71, 0x42, 0xe2, 0x4c, 0xf4, 0x2f, 0xf0, 0x57,
	0xf8, 0x25, 0xfc, 0x2b, 0x14, 0x27, 0x25, 0x69, 0x9b, 0x56, 0x3c, 0xd5, 0xc7, 0xf7, 0xdc, 0x73,
	0x7c, 0xe3, 0xe3, 0x42, 0x2b, 0x4e, 0x39, 0x67, 0x71, 0x2f, 0x8a, 0x43, 0x11, 0xe2, 0xbe, 0xfc,
	0xb9, 0x09, 0x67, 0xe6, 0x31, 0x3c, 0x19, 0x32, 0x71, 0x11, 0xf2, 0x5b, 0xff, 0x2e, 0x8d, 0x3d,
	0xe1, 0x87, 0x9c, 0xb2, 0xef, 0x29, 0x4b, 0x84, 0x79, 0x0b, 0xc6, 0x7a, 0x29, 0x89, 0x42, 0x9e,
	0x30, 0xec, 0xc2, 0x8e, 0x98, 0x47, 0xcc, 0x50, 0x3a, 0x4a, 0xf7, 0xb0, 0x7f, 0xd4, 0x5b, 0xe8,
	0xf5, 0xa8, 0xb4, 0x71, 0xe7, 0x11, 0xa3, 0x92, 0x81, 0x1d, 0xd0, 0xd9, 0x0f, 0xc1, 0x62, 0xee,
	0xcd, 0x46, 0x51, 0x62, 0xa8, 0x9d, 0x66, 0xf7, 0x80, 0x56, 0xb7, 0xcc, 0x5f, 0x2a, 0xe8, 0xe7,
	0x51, 0x34, 0xf3, 0x6f, 0xa4, 0x07, 0x1e, 0x82, 0xea, 0x4f, 0xa5, 0xf2, 0x01, 0x55, 0xfd, 0x29,
	0x9a, 0xd0, 0x9a, 0xb2, 0x68, 0x16, 0xce, 0x03, 0xc6, 0xc5, 0x68, 0x6a, 0xa8, 0xb2, 0xb2, 0xb4,
	0x87, 0x08, 0x3b, 0xdc, 0x0b, 0x98, 0xd1, 0x94, 0x35, 0xb9, 0xc6, 0x23, 0xd8, 0xf5, 0x03, 0xef,
	0x8e, 0x19, 0x3b, 0x72, 0x33, 0x07, 0xd8, 0x86, 0xfd, 0x98, 0x49, 0xb3, 0xc4, 0xd8, 0xed, 0x28,
	0xdd, 0xff, 0xe8, 0x5f, 0x8c, 0x06, 0xec, 0x4d, 0xc3, 0xc0, 0xf3, 0x79, 0x62, 0x68, 0xf2, 0x9c,
	0x0b, 0x88, 0x1f, 0x40, 0x67, 0xfc, 0xc1, 0x8f, 0x43, 0x9e, 0x19, 0x1a, 0x7b, 0x9d, 0x66, 0x57,
	0xef, 0xbf, 0x28, 0xc7, 0xae, 0x9c, 0xbf, 0x67, 0x95, 0x44, 0x8b, 0x8b, 0x78, 0x4e, 0xab, 0xad,
	0xed, 0x77, 0x40, 0x56, 0x09, 0x48, 0xa0, 0x79, 0xcf, 0xe6, 0xc5, 0xc8, 0xd9, 0x32, 0x3b, 0xfb,
	0x83, 0x37, 0x4b, 0x59, 0x31, 0x6c, 0x0e, 0xde, 0xaa, 0x6f, 0x14, 0xd3, 0x01, 0x63, 0x20, 0x27,
	0xaf, 0x58, 0x16, 0x37, 0x86, 0xaf, 0x41, 0xf7, 0xca, 0x5d, 0xa9, 0xa7, 0xf7, 0x1f, 0xd5, 0x9e,
	0x92, 0x56, 0x99, 0xe6, 0x53, 0x38, 0xae, 0x11, 0xcd, 0xef, 0xda, 0x3c, 0xcd, 0x1c, 0x67, 0x4c,
	0xb0, 0x1a, 0xc7, 0x95, 0xbb, 0xca, 0x85, 0xd6, 0xb8, 0x85, 0xd0, 0x19, 0x1c, 0x0f, 0x99, 0xa8,
	0x54, 0x3e, 0x86, 0x77, 0xc9, 0x26, 0xa5, 0xdf, 0x0a, 0xb4, 0xeb, 0xd8, 0x45, 0x00, 0x2f, 0x40,
	0x0b, 0x53, 0x11, 0xa5, 0xa2, 0x88, 0xe0, 0x59, 0x39, 0xe5, 0xe6, 0xae, 0xde, 0x58, 0xb6, 0xd0,
	0xa2, 0x35, 0x4b, 0x8d, 0xf0, 0x83, 0xc5, 0x47, 0x96, 0x6b, 0x7c, 0x0c, 0x9a, 0xf0, 0x92, 0xfb,
	0xd1, 0xb4, 0xc8, 0x52, 0x81, 0xb2, 0x6c, 0x04, 0x2c, 0x49, 0xca, 0x3c, 0x2d, 0xa0, 0xd9, 0x01,
	0x2d, 0xd7, 0x45, 0x00, 0xcd, 0x71, 0x07, 0xe3, 0x89, 0x4b, 0x1a, 0xc5, 0xda, 0xa2, 0x94, 0x28,
	0xa7, 0x3d, 0x80, 0xf2, 0x5d, 0x20, 0x81, 0xd6, 0x60, 0x7c, 0x71, 0x69, 0xd1, 0xaf, 0xce, 0xf5,
	0x39, 0xfd, 0x44, 0x1a, 0x78, 0x08, 0x70, 0x39, 0x79, 0x6f, 0x51, 0xdb, 0x72, 0x2d, 0x87, 0x28,
	0xa7, 0x43, 0x20, 0x95, 0x09, 0x1c, 0xe1, 0x09, 0x86, 0x3a, 0xec, 0x4d, 0xec, 0x4b, 0x7b, 0x7c,
	0x6d, 0x93, 0x46, 0x06, 0x1c, 0x77, 0x7c, 0x75, 0x65, 0x0d, 0x88, 0x82, 0x2d, 0xd8, 0x77, 0xdc,
	0x73, 0xea, 0x8e, 0xec, 0x21, 0x51, 0xb3, 0x12, 0x9d, 0xd8, 0x76, 0x06, 0x9a, 0xfd, 0x9f, 0x4d,
	0xd0, 0x72, 0x67, 0xfc, 0x0c, 0x64, 0xf5, 0x35, 0xe3, 0xb3, 0xa5, 0x8f, 0x56, 0xf7, 0x27, 0xd0,
	0x36, 0xb7, 0x51, 0x8a, 0x7b, 0x6d, 0xe0, 0x17, 0xf8, 0x7f, 0x2d, 0x3f, 0x58, 0x69, 0xdd, 0x94,
	0xd8, 0xf6, 0xc9, 0x56, 0xce, 0xb2, 0xfe, 0x4a, 0xac, 0x96, 0xf5, 0xeb, 0xf3, 0xb9, 0xac, 0xbf,
	0x29, 0x97, 0x0d, 0xbc, 0x01, 0x5c, 0x4f, 0x0d, 0x9e, 0x6c, 0xcf, 0x54, 0xee, 0xf0, 0xfc, 0x5f,
	0x82, 0x67, 0x36, 0x5e, 0x2a, 0xdf, 0x34, 0x49, 0x7c, 0xf5, 0x27, 0x00, 0x00, 0xff, 0xff, 0xa7,
	0x7b, 0x37, 0x7b, 0x8b, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RunnerClient is the client API for Runner service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RunnerClient interface {
	GetConfiguration(ctx context.Context, in *GetConfigurationRequest, opts ...grpc.CallOption) (*GetConfigurationResponse, error)
	DeployApplication(ctx context.Context, in *DeployApplicationRequest, opts ...grpc.CallOption) (*DeployApplicationResponse, error)
	DeleteApplication(ctx context.Context, in *DeleteApplicationRequest, opts ...grpc.CallOption) (*DeleteApplicationResponse, error)
	GetApplicationLogs(ctx context.Context, in *GetApplicationLogsRequest, opts ...grpc.CallOption) (Runner_GetApplicationLogsClient, error)
}

type runnerClient struct {
	cc *grpc.ClientConn
}

func NewRunnerClient(cc *grpc.ClientConn) RunnerClient {
	return &runnerClient{cc}
}

func (c *runnerClient) GetConfiguration(ctx context.Context, in *GetConfigurationRequest, opts ...grpc.CallOption) (*GetConfigurationResponse, error) {
	out := new(GetConfigurationResponse)
	err := c.cc.Invoke(ctx, "/protocol.Runner/GetConfiguration", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerClient) DeployApplication(ctx context.Context, in *DeployApplicationRequest, opts ...grpc.CallOption) (*DeployApplicationResponse, error) {
	out := new(DeployApplicationResponse)
	err := c.cc.Invoke(ctx, "/protocol.Runner/DeployApplication", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerClient) DeleteApplication(ctx context.Context, in *DeleteApplicationRequest, opts ...grpc.CallOption) (*DeleteApplicationResponse, error) {
	out := new(DeleteApplicationResponse)
	err := c.cc.Invoke(ctx, "/protocol.Runner/DeleteApplication", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerClient) GetApplicationLogs(ctx context.Context, in *GetApplicationLogsRequest, opts ...grpc.CallOption) (Runner_GetApplicationLogsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Runner_serviceDesc.Streams[0], "/protocol.Runner/GetApplicationLogs", opts...)
	if err != nil {
		return nil, err
	}
	x := &runnerGetApplicationLogsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Runner_GetApplicationLogsClient interface {
	Recv() (*GetApplicationLogsResponse, error)
	grpc.ClientStream
}

type runnerGetApplicationLogsClient struct {
	grpc.ClientStream
}

func (x *runnerGetApplicationLogsClient) Recv() (*GetApplicationLogsResponse, error) {
	m := new(GetApplicationLogsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RunnerServer is the server API for Runner service.
type RunnerServer interface {
	GetConfiguration(context.Context, *GetConfigurationRequest) (*GetConfigurationResponse, error)
	DeployApplication(context.Context, *DeployApplicationRequest) (*DeployApplicationResponse, error)
	DeleteApplication(context.Context, *DeleteApplicationRequest) (*DeleteApplicationResponse, error)
	GetApplicationLogs(*GetApplicationLogsRequest, Runner_GetApplicationLogsServer) error
}

// UnimplementedRunnerServer can be embedded to have forward compatible implementations.
type UnimplementedRunnerServer struct {
}

func (*UnimplementedRunnerServer) GetConfiguration(ctx context.Context, req *GetConfigurationRequest) (*GetConfigurationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConfiguration not implemented")
}
func (*UnimplementedRunnerServer) DeployApplication(ctx context.Context, req *DeployApplicationRequest) (*DeployApplicationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeployApplication not implemented")
}
func (*UnimplementedRunnerServer) DeleteApplication(ctx context.Context, req *DeleteApplicationRequest) (*DeleteApplicationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteApplication not implemented")
}
func (*UnimplementedRunnerServer) GetApplicationLogs(req *GetApplicationLogsRequest, srv Runner_GetApplicationLogsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetApplicationLogs not implemented")
}

func RegisterRunnerServer(s *grpc.Server, srv RunnerServer) {
	s.RegisterService(&_Runner_serviceDesc, srv)
}

func _Runner_GetConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigurationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServer).GetConfiguration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.Runner/GetConfiguration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServer).GetConfiguration(ctx, req.(*GetConfigurationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runner_DeployApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeployApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServer).DeployApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.Runner/DeployApplication",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServer).DeployApplication(ctx, req.(*DeployApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runner_DeleteApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServer).DeleteApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.Runner/DeleteApplication",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServer).DeleteApplication(ctx, req.(*DeleteApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runner_GetApplicationLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetApplicationLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RunnerServer).GetApplicationLogs(m, &runnerGetApplicationLogsServer{stream})
}

type Runner_GetApplicationLogsServer interface {
	Send(*GetApplicationLogsResponse) error
	grpc.ServerStream
}

type runnerGetApplicationLogsServer struct {
	grpc.ServerStream
}

func (x *runnerGetApplicationLogsServer) Send(m *GetApplicationLogsResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _Runner_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protocol.Runner",
	HandlerType: (*RunnerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetConfiguration",
			Handler:    _Runner_GetConfiguration_Handler,
		},
		{
			MethodName: "DeployApplication",
			Handler:    _Runner_DeployApplication_Handler,
		},
		{
			MethodName: "DeleteApplication",
			Handler:    _Runner_DeleteApplication_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetApplicationLogs",
			Handler:       _Runner_GetApplicationLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "runner.proto",
}
