// Code generated by protoc-gen-go. DO NOT EDIT.
// source: scheduler.proto

package protocol

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ApplicationState int32

const (
	ApplicationState_UNKNOWN  ApplicationState = 0
	ApplicationState_STOPPED  ApplicationState = 1
	ApplicationState_STARTING ApplicationState = 2
	ApplicationState_RUNNING  ApplicationState = 3
)

var ApplicationState_name = map[int32]string{
	0: "UNKNOWN",
	1: "STOPPED",
	2: "STARTING",
	3: "RUNNING",
}

var ApplicationState_value = map[string]int32{
	"UNKNOWN":  0,
	"STOPPED":  1,
	"STARTING": 2,
	"RUNNING":  3,
}

func (x ApplicationState) String() string {
	return proto.EnumName(ApplicationState_name, int32(x))
}

func (ApplicationState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2b3fc28395a6d9c5, []int{0}
}

type TestConnectionRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestConnectionRequest) Reset()         { *m = TestConnectionRequest{} }
func (m *TestConnectionRequest) String() string { return proto.CompactTextString(m) }
func (*TestConnectionRequest) ProtoMessage()    {}
func (*TestConnectionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3fc28395a6d9c5, []int{0}
}

func (m *TestConnectionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestConnectionRequest.Unmarshal(m, b)
}
func (m *TestConnectionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestConnectionRequest.Marshal(b, m, deterministic)
}
func (m *TestConnectionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestConnectionRequest.Merge(m, src)
}
func (m *TestConnectionRequest) XXX_Size() int {
	return xxx_messageInfo_TestConnectionRequest.Size(m)
}
func (m *TestConnectionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TestConnectionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TestConnectionRequest proto.InternalMessageInfo

func (m *TestConnectionRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type TestConnectionResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestConnectionResponse) Reset()         { *m = TestConnectionResponse{} }
func (m *TestConnectionResponse) String() string { return proto.CompactTextString(m) }
func (*TestConnectionResponse) ProtoMessage()    {}
func (*TestConnectionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3fc28395a6d9c5, []int{1}
}

func (m *TestConnectionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestConnectionResponse.Unmarshal(m, b)
}
func (m *TestConnectionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestConnectionResponse.Marshal(b, m, deterministic)
}
func (m *TestConnectionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestConnectionResponse.Merge(m, src)
}
func (m *TestConnectionResponse) XXX_Size() int {
	return xxx_messageInfo_TestConnectionResponse.Size(m)
}
func (m *TestConnectionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TestConnectionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TestConnectionResponse proto.InternalMessageInfo

func (m *TestConnectionResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type DeployApplicationRequest struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Image                string            `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Replicas             uint32            `protobuf:"varint,4,opt,name=replicas,proto3" json:"replicas,omitempty"`
	Environment          map[string]string `protobuf:"bytes,5,rep,name=environment,proto3" json:"environment,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DeployApplicationRequest) Reset()         { *m = DeployApplicationRequest{} }
func (m *DeployApplicationRequest) String() string { return proto.CompactTextString(m) }
func (*DeployApplicationRequest) ProtoMessage()    {}
func (*DeployApplicationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3fc28395a6d9c5, []int{2}
}

func (m *DeployApplicationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeployApplicationRequest.Unmarshal(m, b)
}
func (m *DeployApplicationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeployApplicationRequest.Marshal(b, m, deterministic)
}
func (m *DeployApplicationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeployApplicationRequest.Merge(m, src)
}
func (m *DeployApplicationRequest) XXX_Size() int {
	return xxx_messageInfo_DeployApplicationRequest.Size(m)
}
func (m *DeployApplicationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeployApplicationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeployApplicationRequest proto.InternalMessageInfo

func (m *DeployApplicationRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DeployApplicationRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DeployApplicationRequest) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *DeployApplicationRequest) GetReplicas() uint32 {
	if m != nil {
		return m.Replicas
	}
	return 0
}

func (m *DeployApplicationRequest) GetEnvironment() map[string]string {
	if m != nil {
		return m.Environment
	}
	return nil
}

type DeployApplicationResponse struct {
	State                ApplicationState `protobuf:"varint,1,opt,name=state,proto3,enum=ApplicationState" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *DeployApplicationResponse) Reset()         { *m = DeployApplicationResponse{} }
func (m *DeployApplicationResponse) String() string { return proto.CompactTextString(m) }
func (*DeployApplicationResponse) ProtoMessage()    {}
func (*DeployApplicationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3fc28395a6d9c5, []int{3}
}

func (m *DeployApplicationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeployApplicationResponse.Unmarshal(m, b)
}
func (m *DeployApplicationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeployApplicationResponse.Marshal(b, m, deterministic)
}
func (m *DeployApplicationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeployApplicationResponse.Merge(m, src)
}
func (m *DeployApplicationResponse) XXX_Size() int {
	return xxx_messageInfo_DeployApplicationResponse.Size(m)
}
func (m *DeployApplicationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeployApplicationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeployApplicationResponse proto.InternalMessageInfo

func (m *DeployApplicationResponse) GetState() ApplicationState {
	if m != nil {
		return m.State
	}
	return ApplicationState_UNKNOWN
}

func init() {
	proto.RegisterEnum("ApplicationState", ApplicationState_name, ApplicationState_value)
	proto.RegisterType((*TestConnectionRequest)(nil), "TestConnectionRequest")
	proto.RegisterType((*TestConnectionResponse)(nil), "TestConnectionResponse")
	proto.RegisterType((*DeployApplicationRequest)(nil), "DeployApplicationRequest")
	proto.RegisterMapType((map[string]string)(nil), "DeployApplicationRequest.EnvironmentEntry")
	proto.RegisterType((*DeployApplicationResponse)(nil), "DeployApplicationResponse")
}

func init() { proto.RegisterFile("scheduler.proto", fileDescriptor_2b3fc28395a6d9c5) }

var fileDescriptor_2b3fc28395a6d9c5 = []byte{
	// 380 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0xc1, 0xae, 0xd2, 0x40,
	0x14, 0xa5, 0x2d, 0x68, 0xb9, 0x68, 0x2d, 0x13, 0xc5, 0xd2, 0x15, 0xe9, 0xc6, 0x86, 0xc4, 0x2e,
	0x70, 0x63, 0x5c, 0x98, 0x20, 0x10, 0x62, 0x24, 0x85, 0x4c, 0x4b, 0x4c, 0xdc, 0xd5, 0x72, 0xa3,
	0x4d, 0xcb, 0x4c, 0x6d, 0x07, 0x12, 0x7e, 0xc6, 0x4f, 0x7d, 0x79, 0xe9, 0x14, 0xde, 0xe3, 0xf1,
	0x60, 0x77, 0xcf, 0x9c, 0x33, 0x67, 0xce, 0xdc, 0x7b, 0xe1, 0x4d, 0x19, 0xff, 0xc5, 0xcd, 0x2e,
	0xc3, 0xc2, 0xcb, 0x0b, 0x2e, 0xb8, 0xf3, 0x11, 0xde, 0x85, 0x58, 0x8a, 0x09, 0x67, 0x0c, 0x63,
	0x91, 0x70, 0x46, 0xf1, 0xdf, 0x0e, 0x4b, 0x41, 0xde, 0x42, 0x4b, 0xf0, 0x14, 0x99, 0xa5, 0x0c,
	0x14, 0xb7, 0x4d, 0x6b, 0xe0, 0xb8, 0xd0, 0xbb, 0x94, 0x97, 0x39, 0x67, 0x25, 0x12, 0x03, 0x54,
	0x9e, 0x4a, 0xb1, 0x4e, 0x55, 0x9e, 0x3a, 0x77, 0x0a, 0x58, 0x53, 0xcc, 0x33, 0x7e, 0x18, 0xe7,
	0x79, 0x96, 0xc4, 0xd1, 0xb9, 0xb9, 0x01, 0x6a, 0xb2, 0x39, 0x3a, 0xab, 0xc9, 0x86, 0x10, 0x68,
	0xb2, 0x68, 0x8b, 0x96, 0x2a, 0x4f, 0x64, 0x5d, 0x05, 0x48, 0xb6, 0xd1, 0x1f, 0xb4, 0xb4, 0x3a,
	0x80, 0x04, 0xc4, 0x06, 0xbd, 0x40, 0xe9, 0x57, 0x5a, 0xcd, 0x81, 0xe2, 0xbe, 0xa6, 0x0f, 0x98,
	0x2c, 0xa0, 0x83, 0x6c, 0x9f, 0x14, 0x9c, 0x6d, 0x91, 0x09, 0xab, 0x35, 0xd0, 0xdc, 0xce, 0x68,
	0xe8, 0xdd, 0x4a, 0xe1, 0xcd, 0x1e, 0xc5, 0x33, 0x26, 0x8a, 0x03, 0x3d, 0xbf, 0x6e, 0x7f, 0x05,
	0xf3, 0x52, 0x40, 0x4c, 0xd0, 0x52, 0x3c, 0x1c, 0x83, 0x57, 0x65, 0x95, 0x72, 0x1f, 0x65, 0xbb,
	0x53, 0xf4, 0x1a, 0x7c, 0x51, 0x3f, 0x2b, 0xce, 0x14, 0xfa, 0x57, 0x5e, 0x3e, 0x76, 0xeb, 0x03,
	0xb4, 0x4a, 0x11, 0x09, 0x94, 0x56, 0xc6, 0xa8, 0xeb, 0x9d, 0x89, 0x82, 0x8a, 0xa0, 0x35, 0x3f,
	0x9c, 0x83, 0x79, 0x49, 0x91, 0x0e, 0xbc, 0x5c, 0xfb, 0x3f, 0xfc, 0xe5, 0x4f, 0xdf, 0x6c, 0x54,
	0x20, 0x08, 0x97, 0xab, 0xd5, 0x6c, 0x6a, 0x2a, 0xe4, 0x15, 0xe8, 0x41, 0x38, 0xa6, 0xe1, 0x77,
	0x7f, 0x6e, 0xaa, 0x15, 0x45, 0xd7, 0xbe, 0x5f, 0x01, 0x6d, 0xf4, 0x5f, 0x81, 0x76, 0x70, 0x1a,
	0x3e, 0x99, 0x80, 0xf1, 0x74, 0x8e, 0xa4, 0xe7, 0x5d, 0xdd, 0x03, 0xfb, 0xbd, 0x77, 0x7d, 0xe0,
	0x4e, 0x83, 0x2c, 0xa0, 0xfb, 0xec, 0x87, 0xa4, 0x7f, 0xb3, 0xdf, 0xb6, 0xed, 0xdd, 0x6c, 0x88,
	0xd3, 0xf8, 0x06, 0xbf, 0x74, 0xb9, 0x92, 0x31, 0xcf, 0x7e, 0xbf, 0x90, 0xd5, 0xa7, 0xfb, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x00, 0x7d, 0x01, 0x63, 0xaf, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SchedulerClient is the client API for Scheduler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SchedulerClient interface {
	TestConnection(ctx context.Context, in *TestConnectionRequest, opts ...grpc.CallOption) (*TestConnectionResponse, error)
	DeployApplication(ctx context.Context, in *DeployApplicationRequest, opts ...grpc.CallOption) (*DeployApplicationResponse, error)
}

type schedulerClient struct {
	cc *grpc.ClientConn
}

func NewSchedulerClient(cc *grpc.ClientConn) SchedulerClient {
	return &schedulerClient{cc}
}

func (c *schedulerClient) TestConnection(ctx context.Context, in *TestConnectionRequest, opts ...grpc.CallOption) (*TestConnectionResponse, error) {
	out := new(TestConnectionResponse)
	err := c.cc.Invoke(ctx, "/Scheduler/TestConnection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerClient) DeployApplication(ctx context.Context, in *DeployApplicationRequest, opts ...grpc.CallOption) (*DeployApplicationResponse, error) {
	out := new(DeployApplicationResponse)
	err := c.cc.Invoke(ctx, "/Scheduler/DeployApplication", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SchedulerServer is the server API for Scheduler service.
type SchedulerServer interface {
	TestConnection(context.Context, *TestConnectionRequest) (*TestConnectionResponse, error)
	DeployApplication(context.Context, *DeployApplicationRequest) (*DeployApplicationResponse, error)
}

// UnimplementedSchedulerServer can be embedded to have forward compatible implementations.
type UnimplementedSchedulerServer struct {
}

func (*UnimplementedSchedulerServer) TestConnection(ctx context.Context, req *TestConnectionRequest) (*TestConnectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestConnection not implemented")
}
func (*UnimplementedSchedulerServer) DeployApplication(ctx context.Context, req *DeployApplicationRequest) (*DeployApplicationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeployApplication not implemented")
}

func RegisterSchedulerServer(s *grpc.Server, srv SchedulerServer) {
	s.RegisterService(&_Scheduler_serviceDesc, srv)
}

func _Scheduler_TestConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).TestConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Scheduler/TestConnection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).TestConnection(ctx, req.(*TestConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scheduler_DeployApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeployApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).DeployApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Scheduler/DeployApplication",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).DeployApplication(ctx, req.(*DeployApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Scheduler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Scheduler",
	HandlerType: (*SchedulerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TestConnection",
			Handler:    _Scheduler_TestConnection_Handler,
		},
		{
			MethodName: "DeployApplication",
			Handler:    _Scheduler_DeployApplication_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "scheduler.proto",
}
