// Code generated by protoc-gen-go. DO NOT EDIT.
// source: application.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ApplicationDeleted struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApplicationDeleted) Reset()         { *m = ApplicationDeleted{} }
func (m *ApplicationDeleted) String() string { return proto.CompactTextString(m) }
func (*ApplicationDeleted) ProtoMessage()    {}
func (*ApplicationDeleted) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc846aced8fe6ea6, []int{0}
}

func (m *ApplicationDeleted) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplicationDeleted.Unmarshal(m, b)
}
func (m *ApplicationDeleted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplicationDeleted.Marshal(b, m, deterministic)
}
func (m *ApplicationDeleted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplicationDeleted.Merge(m, src)
}
func (m *ApplicationDeleted) XXX_Size() int {
	return xxx_messageInfo_ApplicationDeleted.Size(m)
}
func (m *ApplicationDeleted) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplicationDeleted.DiscardUnknown(m)
}

var xxx_messageInfo_ApplicationDeleted proto.InternalMessageInfo

func (m *ApplicationDeleted) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ApplicationDeleted) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ApplicationStateChanged struct {
	ApplicationId        string   `protobuf:"bytes,1,opt,name=applicationId,proto3" json:"applicationId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApplicationStateChanged) Reset()         { *m = ApplicationStateChanged{} }
func (m *ApplicationStateChanged) String() string { return proto.CompactTextString(m) }
func (*ApplicationStateChanged) ProtoMessage()    {}
func (*ApplicationStateChanged) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc846aced8fe6ea6, []int{1}
}

func (m *ApplicationStateChanged) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplicationStateChanged.Unmarshal(m, b)
}
func (m *ApplicationStateChanged) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplicationStateChanged.Marshal(b, m, deterministic)
}
func (m *ApplicationStateChanged) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplicationStateChanged.Merge(m, src)
}
func (m *ApplicationStateChanged) XXX_Size() int {
	return xxx_messageInfo_ApplicationStateChanged.Size(m)
}
func (m *ApplicationStateChanged) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplicationStateChanged.DiscardUnknown(m)
}

var xxx_messageInfo_ApplicationStateChanged proto.InternalMessageInfo

func (m *ApplicationStateChanged) GetApplicationId() string {
	if m != nil {
		return m.ApplicationId
	}
	return ""
}

func init() {
	proto.RegisterType((*ApplicationDeleted)(nil), "protocol.ApplicationDeleted")
	proto.RegisterType((*ApplicationStateChanged)(nil), "protocol.ApplicationStateChanged")
}

func init() { proto.RegisterFile("application.proto", fileDescriptor_fc846aced8fe6ea6) }

var fileDescriptor_fc846aced8fe6ea6 = []byte{
	// 128 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4c, 0x2c, 0x28, 0xc8,
	0xc9, 0x4c, 0x4e, 0x2c, 0xc9, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00,
	0x53, 0xc9, 0xf9, 0x39, 0x4a, 0x16, 0x5c, 0x42, 0x8e, 0x08, 0x69, 0x97, 0xd4, 0x9c, 0xd4, 0x92,
	0xd4, 0x14, 0x21, 0x3e, 0x2e, 0xa6, 0xcc, 0x14, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0xa6,
	0xcc, 0x14, 0x21, 0x21, 0x2e, 0x96, 0xbc, 0xc4, 0xdc, 0x54, 0x09, 0x26, 0xb0, 0x08, 0x98, 0xad,
	0x64, 0xcf, 0x25, 0x8e, 0xa4, 0x33, 0xb8, 0x24, 0xb1, 0x24, 0xd5, 0x39, 0x23, 0x31, 0x2f, 0x3d,
	0x35, 0x45, 0x48, 0x85, 0x8b, 0x17, 0xc9, 0x4e, 0x4f, 0x98, 0x49, 0xa8, 0x82, 0x49, 0x6c, 0x60,
	0x47, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x58, 0x1a, 0x3d, 0x82, 0xa0, 0x00, 0x00, 0x00,
}
