// Code generated by protoc-gen-go. DO NOT EDIT.
// source: application_events.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ApplicationStatus int32

const (
	ApplicationStatus_A_UNKNOWN   ApplicationStatus = 0
	ApplicationStatus_A_DEPLOYING ApplicationStatus = 1
	ApplicationStatus_A_RUNNING   ApplicationStatus = 2
	ApplicationStatus_A_CRASHED   ApplicationStatus = 3
	ApplicationStatus_A_FAILED    ApplicationStatus = 4
)

var ApplicationStatus_name = map[int32]string{
	0: "A_UNKNOWN",
	1: "A_DEPLOYING",
	2: "A_RUNNING",
	3: "A_CRASHED",
	4: "A_FAILED",
}

var ApplicationStatus_value = map[string]int32{
	"A_UNKNOWN":   0,
	"A_DEPLOYING": 1,
	"A_RUNNING":   2,
	"A_CRASHED":   3,
	"A_FAILED":    4,
}

func (x ApplicationStatus) String() string {
	return proto.EnumName(ApplicationStatus_name, int32(x))
}

func (ApplicationStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5dbce826b2f4ac8a, []int{0}
}

type ApplicationCreated struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DeploymentId         string   `protobuf:"bytes,2,opt,name=deploymentId,proto3" json:"deploymentId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApplicationCreated) Reset()         { *m = ApplicationCreated{} }
func (m *ApplicationCreated) String() string { return proto.CompactTextString(m) }
func (*ApplicationCreated) ProtoMessage()    {}
func (*ApplicationCreated) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dbce826b2f4ac8a, []int{0}
}

func (m *ApplicationCreated) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplicationCreated.Unmarshal(m, b)
}
func (m *ApplicationCreated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplicationCreated.Marshal(b, m, deterministic)
}
func (m *ApplicationCreated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplicationCreated.Merge(m, src)
}
func (m *ApplicationCreated) XXX_Size() int {
	return xxx_messageInfo_ApplicationCreated.Size(m)
}
func (m *ApplicationCreated) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplicationCreated.DiscardUnknown(m)
}

var xxx_messageInfo_ApplicationCreated proto.InternalMessageInfo

func (m *ApplicationCreated) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ApplicationCreated) GetDeploymentId() string {
	if m != nil {
		return m.DeploymentId
	}
	return ""
}

type ApplicationUpdated struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DeploymentId         string   `protobuf:"bytes,2,opt,name=deploymentId,proto3" json:"deploymentId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApplicationUpdated) Reset()         { *m = ApplicationUpdated{} }
func (m *ApplicationUpdated) String() string { return proto.CompactTextString(m) }
func (*ApplicationUpdated) ProtoMessage()    {}
func (*ApplicationUpdated) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dbce826b2f4ac8a, []int{1}
}

func (m *ApplicationUpdated) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplicationUpdated.Unmarshal(m, b)
}
func (m *ApplicationUpdated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplicationUpdated.Marshal(b, m, deterministic)
}
func (m *ApplicationUpdated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplicationUpdated.Merge(m, src)
}
func (m *ApplicationUpdated) XXX_Size() int {
	return xxx_messageInfo_ApplicationUpdated.Size(m)
}
func (m *ApplicationUpdated) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplicationUpdated.DiscardUnknown(m)
}

var xxx_messageInfo_ApplicationUpdated proto.InternalMessageInfo

func (m *ApplicationUpdated) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ApplicationUpdated) GetDeploymentId() string {
	if m != nil {
		return m.DeploymentId
	}
	return ""
}

type ApplicationDeleted struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RunnerId             string   `protobuf:"bytes,2,opt,name=runnerId,proto3" json:"runnerId,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	DefaultDomain        string   `protobuf:"bytes,4,opt,name=defaultDomain,proto3" json:"defaultDomain,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApplicationDeleted) Reset()         { *m = ApplicationDeleted{} }
func (m *ApplicationDeleted) String() string { return proto.CompactTextString(m) }
func (*ApplicationDeleted) ProtoMessage()    {}
func (*ApplicationDeleted) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dbce826b2f4ac8a, []int{2}
}

func (m *ApplicationDeleted) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplicationDeleted.Unmarshal(m, b)
}
func (m *ApplicationDeleted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplicationDeleted.Marshal(b, m, deterministic)
}
func (m *ApplicationDeleted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplicationDeleted.Merge(m, src)
}
func (m *ApplicationDeleted) XXX_Size() int {
	return xxx_messageInfo_ApplicationDeleted.Size(m)
}
func (m *ApplicationDeleted) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplicationDeleted.DiscardUnknown(m)
}

var xxx_messageInfo_ApplicationDeleted proto.InternalMessageInfo

func (m *ApplicationDeleted) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ApplicationDeleted) GetRunnerId() string {
	if m != nil {
		return m.RunnerId
	}
	return ""
}

func (m *ApplicationDeleted) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ApplicationDeleted) GetDefaultDomain() string {
	if m != nil {
		return m.DefaultDomain
	}
	return ""
}

type ApplicationStatusChanged struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status               ApplicationStatus `protobuf:"varint,2,opt,name=status,proto3,enum=protocol.ApplicationStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ApplicationStatusChanged) Reset()         { *m = ApplicationStatusChanged{} }
func (m *ApplicationStatusChanged) String() string { return proto.CompactTextString(m) }
func (*ApplicationStatusChanged) ProtoMessage()    {}
func (*ApplicationStatusChanged) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dbce826b2f4ac8a, []int{3}
}

func (m *ApplicationStatusChanged) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplicationStatusChanged.Unmarshal(m, b)
}
func (m *ApplicationStatusChanged) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplicationStatusChanged.Marshal(b, m, deterministic)
}
func (m *ApplicationStatusChanged) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplicationStatusChanged.Merge(m, src)
}
func (m *ApplicationStatusChanged) XXX_Size() int {
	return xxx_messageInfo_ApplicationStatusChanged.Size(m)
}
func (m *ApplicationStatusChanged) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplicationStatusChanged.DiscardUnknown(m)
}

var xxx_messageInfo_ApplicationStatusChanged proto.InternalMessageInfo

func (m *ApplicationStatusChanged) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ApplicationStatusChanged) GetStatus() ApplicationStatus {
	if m != nil {
		return m.Status
	}
	return ApplicationStatus_A_UNKNOWN
}

type ApplicationDeploymentRequested struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DeploymentId         string   `protobuf:"bytes,2,opt,name=deploymentId,proto3" json:"deploymentId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApplicationDeploymentRequested) Reset()         { *m = ApplicationDeploymentRequested{} }
func (m *ApplicationDeploymentRequested) String() string { return proto.CompactTextString(m) }
func (*ApplicationDeploymentRequested) ProtoMessage()    {}
func (*ApplicationDeploymentRequested) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dbce826b2f4ac8a, []int{4}
}

func (m *ApplicationDeploymentRequested) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplicationDeploymentRequested.Unmarshal(m, b)
}
func (m *ApplicationDeploymentRequested) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplicationDeploymentRequested.Marshal(b, m, deterministic)
}
func (m *ApplicationDeploymentRequested) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplicationDeploymentRequested.Merge(m, src)
}
func (m *ApplicationDeploymentRequested) XXX_Size() int {
	return xxx_messageInfo_ApplicationDeploymentRequested.Size(m)
}
func (m *ApplicationDeploymentRequested) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplicationDeploymentRequested.DiscardUnknown(m)
}

var xxx_messageInfo_ApplicationDeploymentRequested proto.InternalMessageInfo

func (m *ApplicationDeploymentRequested) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ApplicationDeploymentRequested) GetDeploymentId() string {
	if m != nil {
		return m.DeploymentId
	}
	return ""
}

func init() {
	proto.RegisterEnum("protocol.ApplicationStatus", ApplicationStatus_name, ApplicationStatus_value)
	proto.RegisterType((*ApplicationCreated)(nil), "protocol.ApplicationCreated")
	proto.RegisterType((*ApplicationUpdated)(nil), "protocol.ApplicationUpdated")
	proto.RegisterType((*ApplicationDeleted)(nil), "protocol.ApplicationDeleted")
	proto.RegisterType((*ApplicationStatusChanged)(nil), "protocol.ApplicationStatusChanged")
	proto.RegisterType((*ApplicationDeploymentRequested)(nil), "protocol.ApplicationDeploymentRequested")
}

func init() { proto.RegisterFile("application_events.proto", fileDescriptor_5dbce826b2f4ac8a) }

var fileDescriptor_5dbce826b2f4ac8a = []byte{
	// 302 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x90, 0x51, 0x4f, 0xfa, 0x30,
	0x14, 0xc5, 0xff, 0x0c, 0x42, 0xe0, 0xfe, 0x01, 0x67, 0x9f, 0x1a, 0x4d, 0x8c, 0x59, 0x7c, 0x30,
	0x3e, 0xf0, 0x20, 0x9f, 0xa0, 0x61, 0x28, 0x44, 0x52, 0xcc, 0x90, 0x18, 0x9f, 0x9a, 0x4a, 0xaf,
	0xba, 0x64, 0x6b, 0xe7, 0xd6, 0x99, 0xe8, 0xa7, 0x37, 0x16, 0x41, 0x27, 0x3c, 0xf1, 0xb4, 0xdd,
	0x7b, 0x4e, 0x7e, 0xa7, 0xe7, 0x02, 0x95, 0x59, 0x96, 0xc4, 0x4b, 0x69, 0x63, 0xa3, 0x05, 0xbe,
	0xa1, 0xb6, 0x45, 0x3f, 0xcb, 0x8d, 0x35, 0xa4, 0xe5, 0x3e, 0x4b, 0x93, 0x04, 0x63, 0x20, 0xec,
	0xc7, 0x35, 0xcc, 0x51, 0x5a, 0x54, 0xa4, 0x07, 0x5e, 0xac, 0x68, 0xed, 0xb4, 0x76, 0xde, 0x8e,
	0xbc, 0x58, 0x91, 0x00, 0x3a, 0x0a, 0xb3, 0xc4, 0xbc, 0xa7, 0xa8, 0xed, 0x44, 0x51, 0xcf, 0x29,
	0x95, 0xdd, 0x1f, 0xd2, 0x22, 0x53, 0x7b, 0x93, 0x3e, 0x2a, 0xa4, 0x10, 0x13, 0xdc, 0x45, 0x3a,
	0x82, 0x56, 0x5e, 0x6a, 0x8d, 0xf9, 0x86, 0xb2, 0x99, 0x09, 0x81, 0x86, 0x96, 0x29, 0xd2, 0xba,
	0xdb, 0xbb, 0x7f, 0x72, 0x06, 0x5d, 0x85, 0x4f, 0xb2, 0x4c, 0x6c, 0x68, 0x52, 0x19, 0x6b, 0xda,
	0x70, 0x62, 0x75, 0x19, 0x08, 0xa0, 0xbf, 0xb2, 0xe7, 0x56, 0xda, 0xb2, 0x18, 0xbe, 0x48, 0xfd,
	0xbc, 0xe3, 0x05, 0x03, 0x68, 0x16, 0xce, 0xe0, 0xf2, 0x7b, 0x97, 0xc7, 0xfd, 0xf5, 0x59, 0xfb,
	0x5b, 0x8c, 0xe8, 0xdb, 0x1a, 0xdc, 0xc1, 0x49, 0xa5, 0xdc, 0xba, 0x77, 0x84, 0xaf, 0x25, 0x16,
	0x7b, 0x9e, 0xec, 0x42, 0xc0, 0xe1, 0x56, 0x24, 0xe9, 0x42, 0x9b, 0x89, 0x05, 0xbf, 0xe1, 0xb3,
	0x7b, 0xee, 0xff, 0x23, 0x07, 0xf0, 0x9f, 0x89, 0x70, 0x74, 0x3b, 0x9d, 0x3d, 0x4c, 0xf8, 0xb5,
	0x5f, 0x5b, 0xe9, 0xd1, 0x82, 0xf3, 0xaf, 0xd1, 0x5b, 0x8d, 0xc3, 0x88, 0xcd, 0xc7, 0xa3, 0xd0,
	0xaf, 0x93, 0x0e, 0xb4, 0x98, 0xb8, 0x62, 0x93, 0xe9, 0x28, 0xf4, 0x1b, 0x8f, 0x4d, 0x57, 0x6d,
	0xf0, 0x19, 0x00, 0x00, 0xff, 0xff, 0x5d, 0x7c, 0x0b, 0x2b, 0x54, 0x02, 0x00, 0x00,
}
