// Code generated by protoc-gen-go. DO NOT EDIT.
// source: application.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ApplicationCreated struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DeploymentId         string   `protobuf:"bytes,2,opt,name=deploymentId,proto3" json:"deploymentId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApplicationCreated) Reset()         { *m = ApplicationCreated{} }
func (m *ApplicationCreated) String() string { return proto.CompactTextString(m) }
func (*ApplicationCreated) ProtoMessage()    {}
func (*ApplicationCreated) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc846aced8fe6ea6, []int{0}
}

func (m *ApplicationCreated) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplicationCreated.Unmarshal(m, b)
}
func (m *ApplicationCreated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplicationCreated.Marshal(b, m, deterministic)
}
func (m *ApplicationCreated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplicationCreated.Merge(m, src)
}
func (m *ApplicationCreated) XXX_Size() int {
	return xxx_messageInfo_ApplicationCreated.Size(m)
}
func (m *ApplicationCreated) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplicationCreated.DiscardUnknown(m)
}

var xxx_messageInfo_ApplicationCreated proto.InternalMessageInfo

func (m *ApplicationCreated) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ApplicationCreated) GetDeploymentId() string {
	if m != nil {
		return m.DeploymentId
	}
	return ""
}

type ApplicationUpdated struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DeploymentId         string   `protobuf:"bytes,2,opt,name=deploymentId,proto3" json:"deploymentId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApplicationUpdated) Reset()         { *m = ApplicationUpdated{} }
func (m *ApplicationUpdated) String() string { return proto.CompactTextString(m) }
func (*ApplicationUpdated) ProtoMessage()    {}
func (*ApplicationUpdated) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc846aced8fe6ea6, []int{1}
}

func (m *ApplicationUpdated) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplicationUpdated.Unmarshal(m, b)
}
func (m *ApplicationUpdated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplicationUpdated.Marshal(b, m, deterministic)
}
func (m *ApplicationUpdated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplicationUpdated.Merge(m, src)
}
func (m *ApplicationUpdated) XXX_Size() int {
	return xxx_messageInfo_ApplicationUpdated.Size(m)
}
func (m *ApplicationUpdated) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplicationUpdated.DiscardUnknown(m)
}

var xxx_messageInfo_ApplicationUpdated proto.InternalMessageInfo

func (m *ApplicationUpdated) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ApplicationUpdated) GetDeploymentId() string {
	if m != nil {
		return m.DeploymentId
	}
	return ""
}

type ApplicationDeleted struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RunnerId             string   `protobuf:"bytes,2,opt,name=runnerId,proto3" json:"runnerId,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	DefaultDomain        string   `protobuf:"bytes,4,opt,name=defaultDomain,proto3" json:"defaultDomain,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApplicationDeleted) Reset()         { *m = ApplicationDeleted{} }
func (m *ApplicationDeleted) String() string { return proto.CompactTextString(m) }
func (*ApplicationDeleted) ProtoMessage()    {}
func (*ApplicationDeleted) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc846aced8fe6ea6, []int{2}
}

func (m *ApplicationDeleted) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplicationDeleted.Unmarshal(m, b)
}
func (m *ApplicationDeleted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplicationDeleted.Marshal(b, m, deterministic)
}
func (m *ApplicationDeleted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplicationDeleted.Merge(m, src)
}
func (m *ApplicationDeleted) XXX_Size() int {
	return xxx_messageInfo_ApplicationDeleted.Size(m)
}
func (m *ApplicationDeleted) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplicationDeleted.DiscardUnknown(m)
}

var xxx_messageInfo_ApplicationDeleted proto.InternalMessageInfo

func (m *ApplicationDeleted) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ApplicationDeleted) GetRunnerId() string {
	if m != nil {
		return m.RunnerId
	}
	return ""
}

func (m *ApplicationDeleted) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ApplicationDeleted) GetDefaultDomain() string {
	if m != nil {
		return m.DefaultDomain
	}
	return ""
}

type ApplicationStatusChanged struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApplicationStatusChanged) Reset()         { *m = ApplicationStatusChanged{} }
func (m *ApplicationStatusChanged) String() string { return proto.CompactTextString(m) }
func (*ApplicationStatusChanged) ProtoMessage()    {}
func (*ApplicationStatusChanged) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc846aced8fe6ea6, []int{3}
}

func (m *ApplicationStatusChanged) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplicationStatusChanged.Unmarshal(m, b)
}
func (m *ApplicationStatusChanged) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplicationStatusChanged.Marshal(b, m, deterministic)
}
func (m *ApplicationStatusChanged) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplicationStatusChanged.Merge(m, src)
}
func (m *ApplicationStatusChanged) XXX_Size() int {
	return xxx_messageInfo_ApplicationStatusChanged.Size(m)
}
func (m *ApplicationStatusChanged) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplicationStatusChanged.DiscardUnknown(m)
}

var xxx_messageInfo_ApplicationStatusChanged proto.InternalMessageInfo

func (m *ApplicationStatusChanged) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ApplicationDeploymentRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DeploymentId         string   `protobuf:"bytes,2,opt,name=deploymentId,proto3" json:"deploymentId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApplicationDeploymentRequest) Reset()         { *m = ApplicationDeploymentRequest{} }
func (m *ApplicationDeploymentRequest) String() string { return proto.CompactTextString(m) }
func (*ApplicationDeploymentRequest) ProtoMessage()    {}
func (*ApplicationDeploymentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc846aced8fe6ea6, []int{4}
}

func (m *ApplicationDeploymentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplicationDeploymentRequest.Unmarshal(m, b)
}
func (m *ApplicationDeploymentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplicationDeploymentRequest.Marshal(b, m, deterministic)
}
func (m *ApplicationDeploymentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplicationDeploymentRequest.Merge(m, src)
}
func (m *ApplicationDeploymentRequest) XXX_Size() int {
	return xxx_messageInfo_ApplicationDeploymentRequest.Size(m)
}
func (m *ApplicationDeploymentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplicationDeploymentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ApplicationDeploymentRequest proto.InternalMessageInfo

func (m *ApplicationDeploymentRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ApplicationDeploymentRequest) GetDeploymentId() string {
	if m != nil {
		return m.DeploymentId
	}
	return ""
}

func init() {
	proto.RegisterType((*ApplicationCreated)(nil), "protocol.ApplicationCreated")
	proto.RegisterType((*ApplicationUpdated)(nil), "protocol.ApplicationUpdated")
	proto.RegisterType((*ApplicationDeleted)(nil), "protocol.ApplicationDeleted")
	proto.RegisterType((*ApplicationStatusChanged)(nil), "protocol.ApplicationStatusChanged")
	proto.RegisterType((*ApplicationDeploymentRequest)(nil), "protocol.ApplicationDeploymentRequest")
}

func init() { proto.RegisterFile("application.proto", fileDescriptor_fc846aced8fe6ea6) }

var fileDescriptor_fc846aced8fe6ea6 = []byte{
	// 211 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4c, 0x2c, 0x28, 0xc8,
	0xc9, 0x4c, 0x4e, 0x2c, 0xc9, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00,
	0x53, 0xc9, 0xf9, 0x39, 0x4a, 0x1e, 0x5c, 0x42, 0x8e, 0x08, 0x69, 0xe7, 0xa2, 0xd4, 0xc4, 0x92,
	0xd4, 0x14, 0x21, 0x3e, 0x2e, 0xa6, 0xcc, 0x14, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0xa6,
	0xcc, 0x14, 0x21, 0x25, 0x2e, 0x9e, 0x94, 0xd4, 0x82, 0x9c, 0xfc, 0xca, 0xdc, 0xd4, 0xbc, 0x12,
	0xcf, 0x14, 0x09, 0x26, 0xb0, 0x0c, 0x8a, 0x18, 0x9a, 0x49, 0xa1, 0x05, 0x29, 0x64, 0x9b, 0x54,
	0x85, 0x62, 0x92, 0x4b, 0x6a, 0x4e, 0x2a, 0x36, 0x93, 0xa4, 0xb8, 0x38, 0x8a, 0x4a, 0xf3, 0xf2,
	0x52, 0x8b, 0xe0, 0xa6, 0xc0, 0xf9, 0x42, 0x42, 0x5c, 0x2c, 0x79, 0x89, 0xb9, 0xa9, 0x12, 0xcc,
	0x60, 0x71, 0x30, 0x5b, 0x48, 0x85, 0x8b, 0x37, 0x25, 0x35, 0x2d, 0xb1, 0x34, 0xa7, 0xc4, 0x25,
	0x3f, 0x37, 0x31, 0x33, 0x4f, 0x82, 0x05, 0x2c, 0x89, 0x2a, 0xa8, 0xa4, 0xc5, 0x25, 0x81, 0x64,
	0x77, 0x70, 0x49, 0x62, 0x49, 0x69, 0xb1, 0x73, 0x46, 0x62, 0x5e, 0x3a, 0xa6, 0x0b, 0x94, 0x82,
	0xb8, 0x64, 0x50, 0xdc, 0x09, 0xf3, 0x42, 0x50, 0x6a, 0x61, 0x69, 0x6a, 0x71, 0x09, 0x39, 0x7e,
	0x4f, 0x62, 0x03, 0xc7, 0x8c, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x62, 0xeb, 0x3f, 0x54, 0xb5,
	0x01, 0x00, 0x00,
}
