// Code generated by protoc-gen-go. DO NOT EDIT.
// source: runner_events.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RunnerStatus int32

const (
	RunnerStatus_R_UNKNOWN RunnerStatus = 0
	RunnerStatus_R_ONLINE  RunnerStatus = 1
	RunnerStatus_R_OFFLINE RunnerStatus = 2
)

var RunnerStatus_name = map[int32]string{
	0: "R_UNKNOWN",
	1: "R_ONLINE",
	2: "R_OFFLINE",
}

var RunnerStatus_value = map[string]int32{
	"R_UNKNOWN": 0,
	"R_ONLINE":  1,
	"R_OFFLINE": 2,
}

func (x RunnerStatus) String() string {
	return proto.EnumName(RunnerStatus_name, int32(x))
}

func (RunnerStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_dda6ab8ca21b2faa, []int{0}
}

type RunnerCreated struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RunnerCreated) Reset()         { *m = RunnerCreated{} }
func (m *RunnerCreated) String() string { return proto.CompactTextString(m) }
func (*RunnerCreated) ProtoMessage()    {}
func (*RunnerCreated) Descriptor() ([]byte, []int) {
	return fileDescriptor_dda6ab8ca21b2faa, []int{0}
}

func (m *RunnerCreated) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunnerCreated.Unmarshal(m, b)
}
func (m *RunnerCreated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunnerCreated.Marshal(b, m, deterministic)
}
func (m *RunnerCreated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunnerCreated.Merge(m, src)
}
func (m *RunnerCreated) XXX_Size() int {
	return xxx_messageInfo_RunnerCreated.Size(m)
}
func (m *RunnerCreated) XXX_DiscardUnknown() {
	xxx_messageInfo_RunnerCreated.DiscardUnknown(m)
}

var xxx_messageInfo_RunnerCreated proto.InternalMessageInfo

func (m *RunnerCreated) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type RunnerUpdated struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RunnerUpdated) Reset()         { *m = RunnerUpdated{} }
func (m *RunnerUpdated) String() string { return proto.CompactTextString(m) }
func (*RunnerUpdated) ProtoMessage()    {}
func (*RunnerUpdated) Descriptor() ([]byte, []int) {
	return fileDescriptor_dda6ab8ca21b2faa, []int{1}
}

func (m *RunnerUpdated) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunnerUpdated.Unmarshal(m, b)
}
func (m *RunnerUpdated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunnerUpdated.Marshal(b, m, deterministic)
}
func (m *RunnerUpdated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunnerUpdated.Merge(m, src)
}
func (m *RunnerUpdated) XXX_Size() int {
	return xxx_messageInfo_RunnerUpdated.Size(m)
}
func (m *RunnerUpdated) XXX_DiscardUnknown() {
	xxx_messageInfo_RunnerUpdated.DiscardUnknown(m)
}

var xxx_messageInfo_RunnerUpdated proto.InternalMessageInfo

func (m *RunnerUpdated) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type RunnerDeleted struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RunnerDeleted) Reset()         { *m = RunnerDeleted{} }
func (m *RunnerDeleted) String() string { return proto.CompactTextString(m) }
func (*RunnerDeleted) ProtoMessage()    {}
func (*RunnerDeleted) Descriptor() ([]byte, []int) {
	return fileDescriptor_dda6ab8ca21b2faa, []int{2}
}

func (m *RunnerDeleted) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunnerDeleted.Unmarshal(m, b)
}
func (m *RunnerDeleted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunnerDeleted.Marshal(b, m, deterministic)
}
func (m *RunnerDeleted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunnerDeleted.Merge(m, src)
}
func (m *RunnerDeleted) XXX_Size() int {
	return xxx_messageInfo_RunnerDeleted.Size(m)
}
func (m *RunnerDeleted) XXX_DiscardUnknown() {
	xxx_messageInfo_RunnerDeleted.DiscardUnknown(m)
}

var xxx_messageInfo_RunnerDeleted proto.InternalMessageInfo

func (m *RunnerDeleted) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RunnerDeleted) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type RunnerStatusChanged struct {
	Id                   string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status               RunnerStatus `protobuf:"varint,2,opt,name=status,proto3,enum=protocol.RunnerStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RunnerStatusChanged) Reset()         { *m = RunnerStatusChanged{} }
func (m *RunnerStatusChanged) String() string { return proto.CompactTextString(m) }
func (*RunnerStatusChanged) ProtoMessage()    {}
func (*RunnerStatusChanged) Descriptor() ([]byte, []int) {
	return fileDescriptor_dda6ab8ca21b2faa, []int{3}
}

func (m *RunnerStatusChanged) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunnerStatusChanged.Unmarshal(m, b)
}
func (m *RunnerStatusChanged) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunnerStatusChanged.Marshal(b, m, deterministic)
}
func (m *RunnerStatusChanged) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunnerStatusChanged.Merge(m, src)
}
func (m *RunnerStatusChanged) XXX_Size() int {
	return xxx_messageInfo_RunnerStatusChanged.Size(m)
}
func (m *RunnerStatusChanged) XXX_DiscardUnknown() {
	xxx_messageInfo_RunnerStatusChanged.DiscardUnknown(m)
}

var xxx_messageInfo_RunnerStatusChanged proto.InternalMessageInfo

func (m *RunnerStatusChanged) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RunnerStatusChanged) GetStatus() RunnerStatus {
	if m != nil {
		return m.Status
	}
	return RunnerStatus_R_UNKNOWN
}

func init() {
	proto.RegisterEnum("protocol.RunnerStatus", RunnerStatus_name, RunnerStatus_value)
	proto.RegisterType((*RunnerCreated)(nil), "protocol.RunnerCreated")
	proto.RegisterType((*RunnerUpdated)(nil), "protocol.RunnerUpdated")
	proto.RegisterType((*RunnerDeleted)(nil), "protocol.RunnerDeleted")
	proto.RegisterType((*RunnerStatusChanged)(nil), "protocol.RunnerStatusChanged")
}

func init() { proto.RegisterFile("runner_events.proto", fileDescriptor_dda6ab8ca21b2faa) }

var fileDescriptor_dda6ab8ca21b2faa = []byte{
	// 199 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x2a, 0xcd, 0xcb,
	0x4b, 0x2d, 0x8a, 0x4f, 0x2d, 0x4b, 0xcd, 0x2b, 0x29, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0xe2, 0x00, 0x53, 0xc9, 0xf9, 0x39, 0x4a, 0xf2, 0x5c, 0xbc, 0x41, 0x60, 0x05, 0xce, 0x45, 0xa9,
	0x89, 0x25, 0xa9, 0x29, 0x42, 0x7c, 0x5c, 0x4c, 0x99, 0x29, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c,
	0x41, 0x4c, 0x99, 0x29, 0x08, 0x05, 0xa1, 0x05, 0x29, 0x58, 0x15, 0x18, 0xc3, 0x14, 0xb8, 0xa4,
	0xe6, 0xa4, 0x62, 0x51, 0x20, 0x24, 0xc4, 0xc5, 0x92, 0x97, 0x98, 0x9b, 0x2a, 0xc1, 0x04, 0x16,
	0x01, 0xb3, 0x95, 0x42, 0xb9, 0x84, 0x21, 0x9a, 0x82, 0x4b, 0x12, 0x4b, 0x4a, 0x8b, 0x9d, 0x33,
	0x12, 0xf3, 0xd2, 0xb1, 0x68, 0xd5, 0xe3, 0x62, 0x2b, 0x06, 0x2b, 0x00, 0x6b, 0xe6, 0x33, 0x12,
	0xd3, 0x83, 0x39, 0x5c, 0x0f, 0x59, 0x7b, 0x10, 0x54, 0x95, 0x96, 0x15, 0x17, 0x0f, 0xb2, 0xb8,
	0x10, 0x2f, 0x17, 0x67, 0x50, 0x7c, 0xa8, 0x9f, 0xb7, 0x9f, 0x7f, 0xb8, 0x9f, 0x00, 0x83, 0x10,
	0x0f, 0x17, 0x47, 0x50, 0xbc, 0xbf, 0x9f, 0x8f, 0xa7, 0x9f, 0xab, 0x00, 0x23, 0x44, 0xd2, 0xdf,
	0xcd, 0x0d, 0xcc, 0x65, 0x4a, 0x62, 0x03, 0x1b, 0x6d, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xa6,
	0xf6, 0x46, 0x29, 0x31, 0x01, 0x00, 0x00,
}
