export const INSTAGRAM_FETCH_USER_PENDING = 'INSTAGRAM_FETCH_USER_PENDING'
export const INSTAGRAM_FETCH_USER_SUCCESS = 'INSTAGRAM_FETCH_USER_SUCCESS'
export const INSTAGRAM_FETCH_USER_ERROR = 'INSTAGRAM_FETCH_USER_ERROR'
