# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scheduler.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("scheduler.proto", :syntax => :proto3) do
    add_message "TestConnectionRequest" do
      optional :token, :string, 1
    end
    add_message "TestConnectionResponse" do
      optional :ok, :bool, 1
    end
    add_message "DeployApplicationRequest" do
      optional :id, :string, 1
      optional :name, :string, 2
      optional :image, :string, 3
      optional :replicas, :uint32, 4
      map :environment, :string, :string, 5
    end
    add_message "DeployApplicationResponse" do
      optional :state, :enum, 1, "ApplicationState"
    end
    add_enum "ApplicationState" do
      value :UNKNOWN, 0
      value :STOPPED, 1
      value :STARTING, 2
      value :RUNNING, 3
    end
  end
end

TestConnectionRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("TestConnectionRequest").msgclass
TestConnectionResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("TestConnectionResponse").msgclass
DeployApplicationRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DeployApplicationRequest").msgclass
DeployApplicationResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DeployApplicationResponse").msgclass
ApplicationState = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ApplicationState").enummodule
