# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: scheduler.proto for package ''

require 'grpc'
require 'scheduler_pb'

module Scheduler
  class Service

    include GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'Scheduler'

    rpc :TestConnection, TestConnectionRequest, TestConnectionResponse
    rpc :DeployApplication, DeployApplicationRequest, DeployApplicationResponse
    rpc :DeleteApplication, DeleteApplicationRequest, DeleteApplicationResponse
    rpc :GetApplicationLogs, GetApplicationLogsRequest, stream(GetApplicationLogsResponse)
  end

  Stub = Service.rpc_stub_class
end
