# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: scheduler.proto for package 'protocol'

require 'grpc'
require 'scheduler_pb'

module Protocol
  module Scheduler
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'protocol.Scheduler'

      rpc :TestConnection, TestConnectionRequest, TestConnectionResponse
      rpc :DeployApplication, DeployApplicationRequest, DeployApplicationResponse
      rpc :DeleteApplication, DeleteApplicationRequest, DeleteApplicationResponse
      rpc :GetApplicationLogs, GetApplicationLogsRequest, stream(GetApplicationLogsResponse)
    end

    Stub = Service.rpc_stub_class
  end
end
