export const FETCH_APPLICATIONS_PENDING = 'FETCH_APPLICATIONS_PENDING'
export const FETCH_APPLICATIONS_SUCCESS = 'FETCH_APPLICATIONS_SUCCESS'
export const FETCH_APPLICATIONS_ERROR = 'FETCH_APPLICATIONS_ERROR'

export const ADD_APPLICATION = 'ADD_APPLICATION'
export const UPDATE_APPLICATION = 'UPDATE_APPLICATION'
export const DELETE_APPLICATION = 'DELETE_APPLICATION'

export const CREATE_APPLICATION_PENDING = 'CREATE_APPLICATION_PENDING'
