export const FETCH_APPLICATIONS_PENDING = 'FETCH_APPLICATIONS_PENDING'
export const FETCH_APPLICATIONS_SUCCESS = 'FETCH_APPLICATIONS_SUCCESS'
export const FETCH_APPLICATIONS_ERROR = 'FETCH_APPLICATIONS_ERROR'

export const ADD_APPLICATION = 'ADD_APPLICATION'
